### ISSUE TITLE
Welcome message has no button

### ISSUE THREAD

**Issue by jeff-99** [chiefonboarding/ChiefOnboarding#10]
The pre-boarding welcome message email has no button or link to the portal URL

![image](https://user-images.githubusercontent.com/3385333/88556747-a5ac7200-d029-11ea-9850-3b7c9d9e1a9e.png)

**Comment by GDay** [comment]
Just fixed that one.

![Schermafbeelding 2020-07-27 om 18 00 58](https://user-images.githubusercontent.com/1939656/88564185-6b8ba200-d022-11ea-921c-3b5d54ff6538.png)

Thanks for letting me know!
