### ISSUE TITLE
Postgres issues

### ISSUE THREAD

**Issue by Unknown-Fllooo** [chiefonboarding/ChiefOnboarding#102]
Hello, I'm trying to setup chiefonboarding on a Ubuntu 20 machine with docker. My issue is that the app won't create the Database or tables even though the postgres user has all required permissions and the app connects.

**Comment by Unknown-Fllooo** [comment]
Btw. I tried to manually create the Database which worked so the user definitely has the required permissions the error message which said that the database couldn't be found disappeared.
My docker-compose.yml is almost the same like the default one I only changed settings according the web app.

**Comment by GDay** [comment]
Did the database or app show any errors when it launched? 

Did you also make sure to change the details both in the `db` service and also in the environment variables of the app?

This one in the app environment details:
```
DATABASE_URL=postgres://postgres:postgres@db:5432/chiefonboarding
```
Make sure to keep `db` if you didn't change the name of the database service.

**Comment by GDay** [comment]
Oh, interesting. Yeah, not sure why it didn't create those things immediately, but thanks for letting me know! Good to hear that it is working now for you!
