### ISSUE TITLE
Error: DisallowedHost at Development mode

### ISSUE THREAD

**Issue by lpmtts** [chiefonboarding/ChiefOnboarding#104]
Source code at Master is returning a:

**DisallowedHost at /
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.**

How could I fix that to test in localhost?

**Comment by GDay** [comment]
Either go to `0.0.0.0:8000` instead or add: `ALLOWED_HOSTS: localhost` to this list: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/docker-compose.yml#L25-L32

**Comment by lpmtts** [comment]
> Either go to `0.0.0.0:3000` instead or add: `- ALLOWED_HOSTS=localhost` to this list: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/docker-compose.yml#L25-L32

the 0.0.0.0:3000 dows not work either
![image](https://user-images.githubusercontent.com/46600968/134189502-ebc6dd2d-6cb2-4657-9c59-c6ad0770aa63.png)

I´m running the code in a WSL on Windows, could have something to do with the issue?

Nuxt seams fine, 
![image](https://user-images.githubusercontent.com/46600968/134189915-d0e79b3d-16ea-4895-bac2-58b5ae6e4b7c.png)

Django too
![image](https://user-images.githubusercontent.com/46600968/134190170-4c7eea60-c1ed-4eda-bc08-ca097b0f82f7.png)

**Comment by GDay** [comment]
Nuxt seems to be still compiling, so it could be showing nothing yet. Might take a few minutes before that's done, but yeah, seems like both Django and Nuxt are in good shape. Does `http://0.0.0.0:8000/api/org/` show anything for you?

I am not familiar with WSL at all, so I can't really tell if that could cause issues here.

**Comment by lpmtts** [comment]
Back again with more data.

So I clone the project on Windows now, following the steps on documentation. Containers seem to be working fine, but the error remains, I can't access the URLs in the local machine.

The issue seems to be on the Django application.

This is the call from frontend:

![image](https://user-images.githubusercontent.com/46600968/134261632-3132ab8e-db6f-4c8a-9e59-b1411a536353.png)

This is the URL from the backend
![image](https://user-images.githubusercontent.com/46600968/134261690-30a9d58b-0e3d-4a12-812e-89721d1cacd5.png)

Containers appear to be just fine
Nuxt
![image](https://user-images.githubusercontent.com/46600968/134261769-2d5cf5fd-573d-4836-983d-d4ec5c123cc0.png)

Django
![image](https://user-images.githubusercontent.com/46600968/134261821-8487d61c-12f3-4494-8421-2abd8e3e1735.png)

Any help would be much appreciated, thanks a lot!

**Comment by GDay** [comment]
This is a different error. Seems like it's working now for you. You just need to add 127.0.0.1 to your allowed hosts. 
 
Under `environment` (in that same service) add:
```
- ALLOWED_HOSTS=127.0.0.1
```
Then restart docker (no need to rebuild, just restart). Does that work?

**Comment by GDay** [comment]
This shouldn't be an issue anymore as Nuxt has been removed and this application is now pretty much pure Django (with a few javascript snippets here and there).
