### ISSUE TITLE
Gunicorn listening on 0.0.0.0

### ISSUE THREAD

**Issue by Rigel6** [chiefonboarding/ChiefOnboarding#109]
Hi, sorry about this, I'm pretty sure I'm just not understanding something in the config. 
I'm following the deployment guide here https://docs.chiefonboarding.com/deployment/
I'm running a CentOS 7.9 VM in a ESXi installation. 

I've created a folder called 'chiefonboarding' with two files in it, 'docker-compose.yml' & 'Caddyfile'.
 For the docker-compose.yml file I've edited BASE_URL & ALLOWED_HOSTS to the FQDN of the host (HOSTNAME.DOMAIN.local). I also removed the $PWD variable for the $PWD/Caddyfile:/etc/caddy/Caddyfile line. I was getting an error with this but changing it to the full path fixed the issue. 
For the Caddyfile I replaced 'test.chiefonboarding.com' with the FQDN.
With the exception of the changes mentioned above I've copied the files from the documentation website.

When I run 'docker-compose up' it seems to run through all right but I then get this error.
```
web_1    | [2021-10-22 16:12:36 +0000] [8] [INFO] Starting gunicorn 20.0.4
web_1    | [2021-10-22 16:12:36 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
```

I've tried googling & changing little bits of the config before trying it again but I figure out how to get it to listen on the VM's main IP

**Comment by Rigel6** [comment]
Hi GDay, I spent some time messing with this at the weekend and turns out it was an issue with the FQDN, completely my fault. My apologies for wasting your time.

**Comment by GDay** [comment]
No worries, Rigel6. I am happy to hear that it works for you now!
