### ISSUE TITLE
Hello nginx Service is not running

### ISSUE THREAD

**Issue by thummalaravi** [chiefonboarding/ChiefOnboarding#11]
I have tried to install from Github but Chiefonboarding_nginx service is not running.

**Comment by GDay** [comment]
Hi! Did you see any errors when installing it coming from that container? What does it say when you run `docker start nginx`? Are you running this on a server? If so, what are the specs of that server?

**Comment by GDay** [comment]
I am closing this issue as you haven't responded in over a week. If this is still an issue, then let me know!
