### ISSUE TITLE
[Feature request] Possibility to create condition block for admin task

### ISSUE THREAD

**Issue by gable44** [chiefonboarding/ChiefOnboarding#121]
It would be so awesome if there will be a possibility to create condition block when an admin task is completed. (Not just for To Do items)

**Comment by GDay** [comment]
Hi, sorry for the late reply. I like this feature request, but this will probably take quite some time before it's implement. It's doable, but not super easy to implement. Will see what I can do!

**Comment by GDay** [comment]
This is now made possible through https://github.com/chiefonboarding/ChiefOnboarding/pull/364
