### ISSUE TITLE
Cannot create sequences in Chrome/Brave; Cannot duplicate sequences

### ISSUE THREAD

**Issue by Kuuchuu** [chiefonboarding/ChiefOnboarding#122]
Drag & Drop is not working in the sequence editor in Chrome/Brave. It does work in Firefox.
No Dev Console errors, it simply acts like you highlighted text and are dragging text around.

**Comment by Kuuchuu** [comment]
Sequences also cannot be duplicated. Progress circle spins indefinitely. Every browser

**Comment by GDay** [comment]
v2.0 has been released and you should be able to duplicate sequences there without any issues. It uses plain JavaScript for the drag and drop now, which also should work everywhere (if that would still be an issue).

Let me know if otherwise.
