### ISSUE TITLE
"Always send new hire welcome email" toggle does not work

### ISSUE THREAD

**Issue by Kuuchuu** [chiefonboarding/ChiefOnboarding#123]
![image](https://user-images.githubusercontent.com/20036947/150444580-1d577f20-a575-4842-8639-9b2216888630.png)
Using the above toggle does not seem to make a difference. Welcome email does seem to occasionally send, but maybe only 10% of the time. Sending it manually always works.

**Comment by GDay** [comment]
Thanks for reporting this. You are indeed correct. If you create the new hire on their first day (after 7am their time), then it will send the email. On all other days, it won't. There used to be a scheduled job to trigger the other ones as well, but seems like that got lost along the way. 

I am working on v2.0 (https://github.com/chiefonboarding/ChiefOnboarding/tree/v2.0), which will resolve this. It's not ready yet, but I am fixing the last few bugs there and writting a lot of tests. Scheduled to be released by the end of the month.

In the meantime, I would suggest disabling it and sending the emails manually. Sorry for the inconvenience.

**Comment by Kuuchuu** [comment]
Awesome. All good. Happy to hear a new version is in the works, thanks!

**Comment by GDay** [comment]
v2.0 has been released and this should now be fixed!
