### ISSUE TITLE
Sync With Slack not working as intended

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#124]
Hey 

When I use the Sync with Slack button in the Employee page, the page becomes unresponsive with a red line at the top 

If I refresh the page, I can see that it has managed to import around 80% of the slack users - and giving them access works (but sends an empty message in Slack) 

This is what I can see in the logs during the moment when I press the button and the freeze happens:

`2022-01-26T10:40:27.113264+00:00 app[web.1]: 10.1.5.178 - - [26/Jan/2022:10:40:27 +0000] "POST /api/users/employee/sync_slack HTTP/1.1" 500 145 "https://MYDOMAIN.chiefonboarding/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"`

And this is what I see in Slack: Clicking Resources does nothing, even if that user has resources assigned 

![Screenshot 2022-01-26 at 10 41 56](https://user-images.githubusercontent.com/67741877/151148991-1c2728c5-6ee4-4935-9dcd-89aa24ce0aa0.png)

Apart from that, everything works perfectly fine!

**Comment by GDay** [comment]
This could be two things. 
1. You have a lot of users in Slack and it timed out. Looks like you are using Heroku, which has a timeout of 30 seconds. Can you check if the request did indeed take longer than that?
2. (most likely) the function copies over the "phone" and "position" fields from the users. Looks like Slack isn't providing them at all times (anymore?). 

Will add extra validation for this in the next version.

As for the button not being clickable... does it make a request to the server when you click on the button? It should do that. If not, then check if you configured the app correctly (Slack instructions in the docs).

**Comment by MuratDoganer** [comment]
Thanks for replying :) 

1. I do! Our org is currently at 190 active users, any way to increase the time out in Heroku? - to me it feels instant, the page will freeze, red line will appear at the top, the second I refresh I can see 119 users imported
2. Ah okay, we have the phones field turned off for the org, perhaps that has had an affect...although the users it did import dont have phone data either 

Checking the logs; yes it does make a request to the server

**Comment by GDay** [comment]
Yeah, then it's likely option 2. You cannot increase the timeout in Heroku anyway (and also shouldn't if it would have been possible). Looks like Slack APIs isn't as consistent as I thought. 

Weird that it gets the request in from Slack, but doesn't respond back. I will fix both issues in the new version. I expect to release this in about a week. That would be version 2.0, which will be quite a bit different from the current version. Sneak peak:

![image](https://user-images.githubusercontent.com/1939656/151205320-601a21a9-a8ba-4859-bb2f-a96d3784f76e.png)

**Comment by MuratDoganer** [comment]
Thank you :) 

That looks gorgeous! Great work! 

I noticed in the documentation there isn't any instructions on upgrading, since I deployed to Heroku would this be an automatic process?

**Comment by GDay** [comment]
Good point! I will add that once I push the new version live! In short, you will have to probably have to pull the source to your pc and then push it up to Heroku, like this: https://f-a.nz/dev/update-deploy-to-heroku-app/. 

Alternatively, create a fork of this repo and connect it to Heroku for auto deploys and then also add a script like this for automated syncing when something gets updated on the main branch: https://stackoverflow.com/a/61574295

There aren't any breaking changes (that I have discovered so far), so updating itself should be fairly straightforward.

**Comment by MuratDoganer** [comment]
Awesome, will probably go with Option 1 in this case :) 

Thanks!

**Comment by MuratDoganer** [comment]
Hey

I wonder if this is related to the other Slack issues but have been noticing some strange behaviour today 

1. The bot does not send a message into the Channel to inform of new starter and gather welcome messages
2. The "resources" and "to do" buttons do not function, though messages do get pushed its not formatted in the same way the screenshots show 
3. You cannot talk to the bot, it says Chat is disabled when in the manifest it is not 
4. The initial "welcome" message to the new joiner is not displayed by the bot

It's also not recognising people who have joined Slack 

<img width="693" alt="Screenshot 2022-01-28 at 11 03 45" src="https://user-images.githubusercontent.com/67741877/151536888-2a88025e-5518-495f-a77c-964854117257.png">

<img width="972" alt="Screenshot 2022-01-28 at 11 02 08" src="https://user-images.githubusercontent.com/67741877/151536926-01c6447c-add7-4fe9-993b-b9b5764ecc39.png">

<img width="456" alt="Screenshot 2022-01-28 at 11 10 33" src="https://user-images.githubusercontent.com/67741877/151536995-364df6b4-af53-4670-a8b5-d210422a8c89.png">

**Comment by GDay** [comment]
Apologies for the bumpy road there. Let's see:

> The bot does not send a message into the Channel to inform of new starter and gather welcome messages

> It's also not recognising people who have joined Slack

For security reasons, the bot cannot access any channel (except those that it creates when it chats with users). So you will have to add the bot to the "#general" channel yourself. Just do @<botname> hit return and it will show a dialog and ask to you to add it to the channel. 

![image](https://user-images.githubusercontent.com/1939656/151553177-e2fd35b9-8370-4561-b97a-600634254f08.png)

Should have made this clearer in the docs. This should fix both of the issues above.

> You cannot talk to the bot, it says Chat is disabled when in the manifest it is not

Under "App Home" in the Slack API, there is this option:

![image](https://user-images.githubusercontent.com/1939656/151553566-039982d5-2ec8-42ff-bc21-4afccf921061.png)

If that's not enabled, then messaging the bot does not work. I was under the intention that this was the default, will check that later.

> The initial "welcome" message to the new joiner is not displayed by the bot

The third image you showed is not the one that goes out to new hires, it goes out to normal employees (you have to manually click to give them access (people -> employees -> give access), this is not automated). The new hires message is automated and should send within 15 minutes after a new hire has joined/has been added to the ChiefOnboarding dashboard (this will be instant in v2.0). It matches based on the email address, so that should always be exactly the same.

> The "resources" and "to do" buttons do not function, though messages do get pushed its not formatted in the same way the screenshots show

I am pretty sure this used to be working fine, but for me it doesn't seem to work either. Will investigate and fix this asap. 

> Messaging the bot returns a server 500 error in the logs.

Not happening for me, did you enter something specific or does it not work with anything that you type there?

**Comment by MuratDoganer** [comment]
Ah it has to be in General also, okay! I had it added to a non-default channel so likely why it isnt recognising new joiners 

The Messages Tab is on, but turns out the Allow Users to send Messages box was not ticked (Its off by default btw!) So after ticking that and refreshing Slack it works :) 

Noted about the welcome message, I shall try to do more patient testing haha

After enabling chat; Server 500 error has gone away (so it was linked to the issue above)

But still get server 200 error when requesting `Show me all resources`

But if I type in the resource name directly, it brings it up and you can view it perfectly fine
![Screenshot 2022-01-28 at 13 33 25](https://user-images.githubusercontent.com/67741877/151555674-d92306c4-f982-4cc7-ba49-c7391d7dcc4f.png)

**Comment by GDay** [comment]
Sync with Slack should work fine in v2.0. It's more tolerant to fields that have not been filled in (in Slack).
