### ISSUE TITLE
Request: Change default Slack channel for bot messages

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#126]
Hey! 

Our #general channel is read only for important / urgent announcements 

We use another default public channel for new comers greeting etc, it would be awesome to choose which channel the bot sends the initial welcome the new hire sequence to! 

At the moment it only sends to general :(

**Comment by GDay** [comment]
Good suggestion. Here you go:

![image](https://user-images.githubusercontent.com/1939656/151829551-df23a2b6-95e1-4d5b-9c79-7ae237958a47.png)

Commit: https://github.com/chiefonboarding/ChiefOnboarding/pull/125/commits/2445107cde6b6e186364ceb9c4364b6dbb0a48df

Will be available when I release v2.0 (with a bit of luck at the end of this week).

**Comment by MuratDoganer** [comment]
Perfect, cannot wait to give it a spin!

**Comment by GDay** [comment]
This has been implemented in v2.0.
