### ISSUE TITLE
Request: Assign "To-Dos" for Managers and Buddys

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#129]
Hey! 

I know you can assign To Dos to Admins and the new starter, but can we also have a way to assign them to Managers and Buddy's as well? 

I think this would be really useful for pre-boarding where managers need to do some paper work before the first day etc

**Comment by GDay** [comment]
You will be able to assign it to managers as well in the new version - that's already implemented! For now, you can use this part in the admin task to let someone know of a task:

![image](https://user-images.githubusercontent.com/1939656/158847585-adbd7242-72cd-4b5f-9ef5-90be380b6532.png)

Sorry about the delay on the new version. Still working on that. A few things left to do. I am very close now.

**Comment by MuratDoganer** [comment]
Hey no worries man! Take your time :) 

Nice one, thank you!

**Comment by GDay** [comment]
This is now available in v2.0! 

![image](https://user-images.githubusercontent.com/1939656/178125182-e5ccf92a-fc02-442a-b6d3-5f2b69a4e54e.png)
