### ISSUE TITLE
Bug: Email sequence item uses recipients information to fill out the template {{last_name}}, {{first_name}}, etc.

### ISSUE THREAD

**Issue by ropelletier** [chiefonboarding/ChiefOnboarding#130]
![image](https://user-images.githubusercontent.com/88781432/159325938-119f812f-bb82-4ac5-b9b2-ecf6d8650773.png)

I am testing the Email sequence item out and I assumed that these expressions {{first_name}} would come from the new hire. But instead they translate to the name of the person I am sending the Email to, which makes no sense to me at all. I have to assume this is a bug or I am doing it wrong.

For example, 
The employee "IT Department" has the first name IT and last name Department and their position is IT Department.
The new hire has the first name "Test" and last name "User"

This is the email subject  that the Use "IT Department" received, which is telling them they were hired for a position they already have. :-)

"New Hire - IT Department IT Department"

Any thoughts

**Comment by GDay** [comment]
Yikes, that's a nasty bug! I guess that's what I get for not having a decent test suite (v2.0 will have that, for sure). Currently pushing a fix for this.

**Comment by GDay** [comment]
Thanks for reporting this, I have no clue how I never noticed this bug before. Please update your instance to get the fixed version!

**Comment by ropelletier** [comment]
Works great. Well done. I have found a few other bugs that I will report when I have a few minutes. This is a very promising project and I really appreciate your very quick reponse.
