### ISSUE TITLE
Clarify that adding new Slack accounts is an Enterprise-only feature

### ISSUE THREAD

**Issue by Keanu73** [chiefonboarding/ChiefOnboarding#138]
Hi,

Currently I was in the process of setting up ChiefOnboarding for the company I work for, however, an important caveat that's missing from the documentation is that, as of May 2020, the "legacy" endpoint that used to allow you to invite users is not available to workspaces that are not on the Enterprise plan. Since our workspace is on the Pro plan, I feel that this kind of defeats the point of ChiefOnboarding, since the ability for it to automatically create Slack/G Suite accounts was the main reason I thought this would be worth setting up in the first place.

https://stackoverflow.com/questions/30955818/slack-api-team-invitation

**Comment by GDay** [comment]
Oh, I am sorry about that! Looks like you are right. The current integration still assumes that people are able to make those legacy keys, it's also not ready for the Enterprise plan either. 

I have just updated the docs and removed the instructions there. When the new version is out (PR), I will also update the other info to make this more clear.

Thanks for reporting this!

**Comment by GDay** [comment]
There is now a banner on the Slack integration page, so I am closing this issue.

![image](https://user-images.githubusercontent.com/1939656/187794754-1fe03d01-8ff7-4f77-8549-4269f301656a.png)
