### ISSUE TITLE
feature request: microsoft office 365 user provisioning support

### ISSUE THREAD

**Issue by zombiehoffa** [chiefonboarding/ChiefOnboarding#139]
Would be awesome if this could create office365 business users.

**Comment by GDay** [comment]
Yeah, nice one! Will add it to the backlog. Thanks.

**Comment by JOHLC** [comment]
Also would be interested in this

**Comment by GDay** [comment]
This will probably be possible with the new webhook/integration feature in version 2.0. I will write up the json config file for that when I release v2.0 (next week). 

An example of an integration of a different service: https://integrations.chiefonboarding.com/d/1-asana-account-creation

**Comment by GDay** [comment]
I still need to workout the error handling, but I have made a config file for Azure Active Directory. I am not really familiar with the microsoft offering, but I think that automatically creates an office account as well(?). It will call this API: https://docs.microsoft.com/en-us/graph/api/user-post-users

Here is the config file: https://integrations.chiefonboarding.com/d/16-azure-active-directory-account-creation-beta (this needs the currently open (WIP) PR #212 to work. Will merge that PR later this week.

**Comment by GDay** [comment]
Apologies for the delay. I have just merged that PR. So this integration should be possible and working now with the JSON code from the link.
