### ISSUE TITLE
Documentation for contributers

### ISSUE THREAD

**Issue by gb-kpatel** [chiefonboarding/ChiefOnboarding#142]
I think this project is missing documentation and guidelines for contributors. It should have some steps for project setup that will help contributors for a quick start.

**Comment by GDay** [comment]
Yeah, you are definitely right! I am in the process of getting a big update out (v2.0), which will simplify the codebase a lot. Once that's out, I will write some contributors guidelines and also an architecture.md file to make it easier to understand how things work under the hood.
Thanks!
