### ISSUE TITLE
[Feature Request] Change email style

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#144]
Hey @GDay Hope the work on v2 is going okay! 

I just wanted to see if this was possible at all;

Allowing admins to change the style of the email (possibly by pasting in HTML?) so that it can better match the brand of the organisation? 

We use several custom html email templates to make sure emails sent by the system are consistent with the brand, by ChiefOnBoarding has its own style which many users ignore thinking its phishing :D 

Thanks!

**Comment by GDay** [comment]
Oh, interesting. Yeah, that should be fairly easy. Will incorporate that into v2.0. Thanks for that suggestion.

All features have been migrated to v2.0 (except the one you proposed now), I am currently adding tests - at 75% test coverage right now and fixing some bugs that I find along the way. It's getting there!

**Comment by MuratDoganer** [comment]
Thank you! 

Ah thats amazing, let me know how I can donate :)

**Comment by GDay** [comment]
This has been implemented in v2.0. Docs for email format (included tags for dynamic content): https://docs.chiefonboarding.com/deployment/#custom-email-template
