### ISSUE TITLE
Hardcoded from header

### ISSUE THREAD

**Issue by qzaidi** [chiefonboarding/ChiefOnboarding#146]
https://github.com/chiefonboarding/ChiefOnboarding/blob/af3711931a41b436ea16b896a5f3eb52ae652cfd/back/user_auth/serializers.py#L10

This look like a bug - the header too should reflect the value set in DEFAULT_FROM_EMAIL

**Comment by GDay** [comment]
Oh. Thanks for reporting that. You are indeed right, that should have been `settings.DEFAULT_FROM_EMAIL`. 

I will get this fixed ASAP.

**Comment by GDay** [comment]
Fixed! Please update your instance to v1.2.23!
