### ISSUE TITLE
Fix a typo with bool

### ISSUE THREAD

**Issue by nilend** [chiefonboarding/ChiefOnboarding#147]
https://github.com/chiefonboarding/ChiefOnboarding/blob/06712bf6059f8feb183f410af96c4a31a42c92f7/back/back/settings.py#L266

This should be replaced by `bool`.

**Comment by GDay** [comment]
Thanks! It looks like you are referencing a file from the v2.0 branch. That branch is not yet ready for production (will be soon though). I will get that typo fixed though. Just know that you might encounter more bugs!
Thanks again for letting me know!

**Comment by GDay** [comment]
Closing this as v2.0 got released.
