### ISSUE TITLE
Move resources loaded from a CDN to local

### ISSUE THREAD

**Issue by GDay** [chiefonboarding/ChiefOnboarding#15]
#### Problem
Loading resources from content delivery networks could result in privacy issues. Next to privacy, safety could also be improved by removing the external resources.

### Solution
Import the resources from the assets in the app itself instead of relying on the CDN. There are currently four resources that rely on external servers. 

These are the links that should be replaced by local files:

```
https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap
https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons
https://use.fontawesome.com/releases/v5.0.13/css/all.css
https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css
```

**Comment by chmey** [comment]
I'll do it for you.

**Comment by GDay** [comment]
Awesome, thank you!

**Comment by chmey** [comment]
I cannot build the containers because I am missing the environment setup (SECRET_KEY, ALLOWED_HOST, etc.)

Your docs don't show that any step is required, how can I quickly create a dev environment so I can build the images?

**Comment by GDay** [comment]
Oh, dang it. I might have accidentally removed that part when I moved the docs from the `README.md` to the other documentation repo. Easiest way is to use the `.env.example` file that can be found in the `back/back/` folder. Remove `.example` from it and you should be good to go.

Will update the docs in a minute.

**Comment by chmey** [comment]
I am withdrawing from this because I cannot really set up the development environment. Maybe it works better if you or somebody else takes it. 
Cheers!
