### ISSUE TITLE
Email task Subject variables not resolving

### ISSUE THREAD

**Issue by ropelletier** [chiefonboarding/ChiefOnboarding#184]
I am testing out the Email Sequence Task. The body is resolving the variables without issue, but the subject is not.

![image](https://user-images.githubusercontent.com/88781432/178738395-01e132c3-2714-4dc1-8980-d13dea9add60.png)

![image](https://user-images.githubusercontent.com/88781432/178738764-a68aff9e-1958-4213-8484-cf15e676c2a6.png)

**Comment by GDay** [comment]
Thanks for letting me know. I have just added support for this. Please update to the latest version.
