### ISSUE TITLE
ACCOUNT_EMAIL & ACCOUNT_PASSWORD env variables & Password Reset all not working

### ISSUE THREAD

**Issue by ropelletier** [chiefonboarding/ChiefOnboarding#187]
I decided to wipe my database and start fresh with v2, but the ACCOUNT_EMAIL & ACCOUNT_PASSWORD env variables do not create an account (seemingly). When I try to use the password reset link I get 

![image](https://user-images.githubusercontent.com/88781432/178756159-058ad728-5287-4bb6-b900-e99c11654e8c.png)

Also, when I do not use the ACCOUNT_EMAIL & ACCOUNT_PASSWORD env variables I do not see an account being created in the logs.

**Comment by GDay** [comment]
Thanks for reporting this. Looks like there is a fix for this in PR #188. Once that's merged, I will try a fresh install on Heroku and check if there are more issues.

**Comment by GDay** [comment]
Apologies for that. Looks like I missed that during testing. This has now been fixed! The variables work now and also password reset works now!

**Comment by Kuuchuu** [comment]
@GDay Has this fix been pushed to the latest docker image? I seem to be having the same issue.

**Comment by GDay** [comment]
@Kuuchuu Sorry, I forgot to run the docker trigger (and it also got skipped when I tried). Pushed a fix, it runs now, should be up in a minute. Once you have pulled in the new image, recreate your database and then you should be good to go.
