### ISSUE TITLE
Cannot Send Preboarding Email or Login Email

### ISSUE THREAD

**Issue by Kuuchuu** [chiefonboarding/ChiefOnboarding#196]
Attempting to send the Preboarding Email results in a greyed out "Send Type" combo box and a "This field is required" error upon attempting to send it:
![image](https://user-images.githubusercontent.com/20036947/180132526-353679d3-8501-4b60-8dcc-542cb6c329fa.png)
Attempting to send the Login Email results in "Forbidden (403) CSRF verification failed. Request aborted":
![image](https://user-images.githubusercontent.com/20036947/180132664-ad34441d-c925-4d47-bd92-ef4491115e97.png)
I have confirmed the SMTP settings work, invite emails were automatically sent to the administrator account when it was created.
Is there something obvious I'm missing? Something I need to configure for the new hire user?
Thanks!

**Comment by GDay** [comment]
Thanks for reporting this! Those are both bugs. I have just created a PR that I will merge in about an hour and then this should be fixed for you!

**Comment by GDay** [comment]
Merged and also updated the docker image ;)
