### ISSUE TITLE
Way for users to upload files

### ISSUE THREAD

**Issue by rjh360** [chiefonboarding/ChiefOnboarding#197]
Hi, 
Love the new version 2 of the software. However is there anyway that users are able to upload their own files on the workflow? For example if they have an application form they have signed and need to upload to the system for the HR department to view properly, is this possible from the UI?

**Comment by GDay** [comment]
There is! When you go into a to do item or preboarding item, you can create a new line in the content box and then click on the form icon:

![image](https://user-images.githubusercontent.com/1939656/180232940-56264df8-32b7-4df9-8952-c632a677cab8.png)

Then click on the options icon and then select file upload:

![image](https://user-images.githubusercontent.com/1939656/180233313-620813b1-2f68-4292-8680-a34d210d93c4.png)

When a user uploaded a file, you can go to their "forms" and then download the file there:

![image](https://user-images.githubusercontent.com/1939656/180233559-7831d9c1-7fad-4a1d-9a15-f63a8a6b38c8.png)

Is that what you want to do?

**Comment by reiniertc** [comment]
I have a form where the new_hire can upload a document. 
Ik I look at the minio console, the document is uploaded.
But when I look at the form results, there is no download button

**Comment by GDay** [comment]
@reiniertc This is working fine for me: 

![afbeelding](https://github.com/chiefonboarding/ChiefOnboarding/assets/1939656/e43346be-bc1a-4198-a9c6-a35a9aa3c2da)

Just tested it with a new to do item. Did you also "complete" the todo item?

**Comment by reiniertc** [comment]
Hmm... the issue seems to be that when I press the "submit" button, that it doesnt do anything.
I had multiple forms on a page and only 1 part was able to submit using the button.
Now I have 1 form (and 1 button), including a field for uploading the doc, and: it works :-)

Thx!
