### ISSUE TITLE
Feature Request: Customise COB Bot's message in Slack

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#215]
Hey,

It would be great if there was a way to customise the message that gets sent to the onboarding channel in slack by the COB Bot. It would be great if we could use {{ first_name }} {{ manager }} {{ department }} etc while editing! 

Use case: Just to provide a tiny bit more info, like job title, department etc

**Comment by GDay** [comment]
> the message

What message exactly? 

It sends: 

> Just a quick reminder: It's %(name)s's first day today!

And this:

> We have a new hire coming in soon! Make sure to leave a message for %(first_name)s!

--- 

Also, a little hacky, but should work: 

You could create a new employee account (with a random/fake email address) and then go into console and set the `slack_user_id` of that user to a channel name, i.e. `#general`. 

Then, in the sequences, you can add a custom Slack message and select that new user and add whatever you want in it. That should then send a message to the channel.

**Comment by GDay** [comment]
Nevermind that hacky workaround. When I merge #217, you can send a message to a Slack channel instead of a specific user (and use the new hire's context). You could add this to a new hire's first day sequence block and that would pretty much simulate the `Just a quick reminder: It's %(name)s's first day today!` message.

**Comment by MuratDoganer** [comment]
Ah it was the second one! The channel wide one where colleagues can leave comments :) 

Ill give that a go, thank you!

**Comment by GDay** [comment]
> Ah it was the second one!

So, for the second one, you can use the "message" area: 
![image](https://user-images.githubusercontent.com/1939656/184358005-2430a23f-24a6-40bb-9ad3-d7b2824a0bc3.png)

That area does support the context items as well, so you can use `{{ manager }}`, `{{ department }} etc there. That's the "Derek is our new developer..." part in the screenshot:

![image](https://user-images.githubusercontent.com/1939656/184358262-d424369d-60c1-4210-bc32-83ca5256314e.png)

Would a default message (defined in the settings) solve this for you? Or would you rather change the "Derek starts on..." part?

**Comment by MuratDoganer** [comment]
I think with combination of the workaround you added + the default we are good! we just wanted to expand on a few more details - I didnt realise we could use context in that Message section so that does help a ton! 

Ill close this as I think we are able to do this effectively now :) Thanks @GDay !

**Comment by GDay** [comment]
Great! I have merged the PR this morning, so when you update your instance, you can send messages to channels without the workaround!

![image](https://user-images.githubusercontent.com/1939656/184359963-1d8ff0cf-8389-4358-b566-f61c260b6b05.png)
