### ISSUE TITLE
AWS S3 access forces use of access / secret keys vs using role

### ISSUE THREAD

**Issue by zonywhoop** [chiefonboarding/ChiefOnboarding#236]
If AWS_ACCESS_KEY_ID is not set then S3 file access is disabled.  It's also being directly used when creating the boto object. Using AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are not required when using boto if something like AWS_PROFILE is defined in the environment or if the instance/pod is configured using an AWS role.  Boto by default will traverse all credential attempts (including using AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY) from the environment if they are not strictly provided. Can requirement of these be removed and instead just look to ensure that AWS_REGION and AWS_STORAGE_BUCKET_NAME are set?

**Comment by GDay** [comment]
Thanks for that suggestion! I have never worked with a AWS profile, but that makes sense to me. Didn't know that boto3 would look up the the credentials by itself. I have just created a PR that should fix this. See #237. 

Will merge that later today or tomorrow.

**Comment by vakninr** [comment]
@GDay - Actually I was looking for just that fix when I explored the repo. I suggest to update the documentation as well for the deployment. I couldn't find anything related using roles in the S3 set up. 

Thanks

**Comment by GDay** [comment]
@vakninr Thanks, I appreciate the heads-up. I have just updated the docs: https://github.com/chiefonboarding/ChiefOnboarding/pull/318
