### ISSUE TITLE
[Request] "Send Test Email" button

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#241]
Hey G'day,

It would be super handy if there was a way to send test emails to yourself from the system with a click of a button so you can see what the end result will look like without having to create loads of new employees to trigger it with! 

Use Case: I want to know what it looks like for a new starter, and the different types of emails we send them, without having to create new accounts all the time!

**Comment by GDay** [comment]
Thanks! Yeah, that's a good suggestion. Will see what I can do!

**Comment by GDay** [comment]
Done! This works now for welcome messages (settings -> welcome messages) and within sequences (for email/text/slack messages).
