### ISSUE TITLE
Server 500 Error when clicking Resources

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#242]
Hey @GDay 

Came across a new issue today, some of our resource items stopped responding randomly with no changes from our side 

In the web app, clicking Resources (as a new hire) causes a Server 500 error

In Slack the wheel just spins (logs also show a Server 500 error) when you click on Resources 

We are also seeing a course get "Unable to connect" error as well

This happened quiet recently, seemingly out of the blue (as we had a few new starters go through without issue)

**Comment by GDay** [comment]
Hey @MuratDoganer, 

That's not good, sorry to hear that. Without any details on the error, I don't really know why this is happening. Let's get the resources manually through shell:

Go to the new hire who got the error (in admin) and copy the id from the URL (referenced as "new_hire_id" going forward).

Then in shell:

```
from admin.resources.models import Resource
from users.models import User, ResourceUser

user = User.objects.get(id=new_hire_id)
ResourceUser.objects.filter(user=user).order_by("resource__category").select_related("resource__category").prefetch_related("resource__chapters")
```

That should return a `Queryset`. Check if it doesn't do that.

Up next, let's check for one edge case (this could cause the 500 error, but I am uncertain how you would be able to create this):

In the same shell:

```
ResourceUser.objects.filter(user=user, resource__isnull=True).exists()
```
That should give `False`.

If that all passes, then let's check if all resources have indeed at least one chapter (which is a requirement):

```
from django.db.models import Count
Resource.objects.annotate(num_chapters=Count('chapters')).filter(num_chapters=0)
```
There shouldn't be a way to create a resource without chapters, but maybe you hit an edge case somehow. 
It will print out a `Queryset` with the `id` of the resource in that. There should be none. If there is one, then that's likely the issue (if it's also assigned to the new hire that's having this issue).

**Comment by MuratDoganer** [comment]
Okay, here is the print out from those tests:

```>>> from admin.resources.models import Resource
>>> from users.models import User, ResourceUser
>>> 
>>> user = User.objects.get(id=135)
>>> ResourceUser.objects.filter(user=user).order_by("resource__category").select_related("resource__category").prefetch_related("resource__chapters")
<QuerySet [<ResourceUser: ResourceUser object (14)>, <ResourceUser: ResourceUser object (9)>, <ResourceUser: ResourceUser object (11)>, <ResourceUser: ResourceUser object (3)>, <ResourceUser: ResourceUser object (12)>, <ResourceUser: ResourceUser object (4)>, <ResourceUser: ResourceUser object (10)>, <ResourceUser: ResourceUser object (5)>, <ResourceUser: ResourceUser object (13)>, <ResourceUser: ResourceUser object (8)>, <ResourceUser: ResourceUser object (6)>, <ResourceUser: ResourceUser object (71)>, <ResourceUser: ResourceUser object (15)>]>
>>> ResourceUser.objects.filter(user=user, resource__isnull=True).exists()
False
>>> from django.db.models import Count
>>> Resource.objects.annotate(num_chapters=Count('chapters')).filter(num_chapters=0)
<QuerySet [<Resource: Resource object (19)>, <Resource: Resource object (21)>, <Resource: Resource object (18)>]>

I am going to do another check in a moment, it seems 2 people are having issues with Resources but I cannot personally replicate it on my account

**Comment by MuratDoganer** [comment]
Yeah that is strange

I just created a test user and got the same issue right away

```
GET https://firstday.landtech.systems/new_hire/resources/ 500
```
In the console log, not much info in the network tab either (using Chrome to troubleshoot)

**Comment by GDay** [comment]
These are likely items in sequences. Check the sequences that gets added to the new hire directly If they are not templates, then they don't show up in the templates list and are not accessible that way. You can check the dev tools in your browser (network tab) for the ids when you click on one)

**Comment by GDay** [comment]
Okay, what if you do:

```
from users.models import User, ResourceUser

user = User.objects.get(id=135)
for resource_user in ResourceUser.objects.filter(user=user):
    print(f"{resource_user.resource.id} - {resource_user.resource.id}")
```
That should reveal the name of the resource that's not working. The id should be any of the `19`, `21` or `18`.

**Comment by MuratDoganer** [comment]
Okay this was the output:

```
>>> from users.models import User, ResourceUser
>>> 
>>> user = User.objects.get(id=135)
>>> for resource_user in ResourceUser.objects.filter(user=user):
...     print(f"{resource_user.resource.id} - {resource_user.resource.name}")
... 
18 - Compliance and Security Training
8 - Induction: Finance
11 - Induction: Marketing
15 - Induction: Vision, Mission and Values
12 - Induction: New Business
10 - Induction: IT & Systems
9 - Induction: International
16 - Product Demos
13 - Induction: People Operations
14 - Induction: Product
7 - Induction: Engineering
5 - Induction: Business Operations
20 - Induction: Customer Growth
```

So pretty much all of the resources

**Comment by GDay** [comment]
> 18 - Compliance and Security Training

That's the issue. It's `18`.

**Comment by GDay** [comment]
It probably has 0 chapters.

**Comment by MuratDoganer** [comment]
Odd, there is chapters inside that resource (view below direct from Sequence)

<img width="1096" alt="Screenshot 2022-09-28 at 16 25 03" src="https://user-images.githubusercontent.com/67741877/192820048-689b171e-129b-42ff-90a1-4599226db2a9.png">

**Comment by MuratDoganer** [comment]
Could it be due to the numbers in the Chapter titles?

**Comment by GDay** [comment]
Wow. Very strange. I will quickly create a new branch to see if my suspicion is right. 

No, numbers don't matter there.

**Comment by GDay** [comment]
Can you try to push this branch? https://github.com/chiefonboarding/ChiefOnboarding/pull/243
You can see the diff. I believe it fails on that, because it can't get the `id` of a chapter, because there are none.

**Comment by MuratDoganer** [comment]
I might be being blind but that commit isnt coming up for me in render

**Comment by GDay** [comment]
Branch `GDay-patch-1`?

**Comment by GDay** [comment]
Maybe tests need to pass? It failed on codecov upload (when doesn't it? lol). Rerunning tests now, maybe it shows up then.

**Comment by MuratDoganer** [comment]
lol true 

Let me just clear render and try again, this happens sometimes!

**Comment by MuratDoganer** [comment]
Ah okay yeah its there but currently getting this error on deploy

```
tar: Exiting with failure status due to previous errors
```

**Comment by GDay** [comment]
Weird, worked fine when I pushed it to heroku. Can you try again? Perhaps something at Render went wrong?

**Comment by MuratDoganer** [comment]
Okay so, that fixed it, to an extent. Now the behaviour has shifted a little:

- `18 - Compliance and Security Training` < This resource still brings a 404 error 
- One of the courses (Vision, Mission, Values) suddenly has the questions section missing
- One of the courses is missing (`20 - Induction: Customer Growth`) from the rouses tab (web app)

**Comment by GDay** [comment]
Okay, so my assumption as right. Great. Still not sure why it shows correctly in the sequences. 

> 18 - Compliance and Security Training < This resource still brings a 404 error

This is normal, because I put the `id` of the first chapter to `0`, which doesn't exist. Somehow this one doesn't have chapters in your account, but it does in the sequence. Weird.

> One of the courses (Vision, Mission, Values) suddenly has the questions section missing

These questions are available in the sequence?

> from the rouses tab (web app)

You mean from the sidebar?

**Comment by MuratDoganer** [comment]
> These questions are available in the sequence?
Yes, still available when in sequence, just not for the candidate

>from the rouses tab (web app)
Correct, it was there before, now its not, but it is still in the sequence

**Comment by MuratDoganer** [comment]
Looks good so far, I did get `admin.resources.models.Resource.DoesNotExist: Resource matching query does not exist` but was fine to migrate anyway as they are unlikely to be used 

As for the other new issues, seems like the latest deploy fixed those too!

**Comment by MuratDoganer** [comment]
Not sure if its due to the latest change but this happened now:

View in COB Editor:
<img width="841" alt="Screenshot 2022-09-29 at 12 20 28" src="https://user-images.githubusercontent.com/67741877/193018792-6427a36e-c293-4f92-8e8a-ce5881f5955f.png">

View in Web:
<img width="836" alt="Screenshot 2022-09-29 at 12 20 49" src="https://user-images.githubusercontent.com/67741877/193018815-7f58f2c8-61b0-4a16-a3f2-9c835fc77ac4.png">

View in Slack:
<img width="514" alt="Screenshot 2022-09-29 at 12 21 09" src="https://user-images.githubusercontent.com/67741877/193018840-867bf038-0491-4fcc-9b95-c77753440c7d.png">

**Comment by GDay** [comment]
Good to hear that the resource issue is gone. 

No, that's actually not related. Not sure when that happened. But here is the fix for the web page:
https://github.com/chiefonboarding/ChiefOnboarding/pull/243/commits/5159a1777ee0887e05902c5262af99678acb0706

And here is the fix for the slack thing (Slack only happened with list items, not with normal text):
https://github.com/chiefonboarding/ChiefOnboarding/pull/243/commits/d6636d091c7c19794eef7f80e6d612660e3032ba

Or just deploy the latest commit on the branch you have already deployed and it should be working again. Sorry about that. Thanks for letting me know.

**Comment by GDay** [comment]
Regarding that list line though: the "*all *modules" doesn't work because there is a space behind the "all" that is within the bold. If you move the space after the *, then it should be bold.
