### ISSUE TITLE
[Request] Automatically wish birthdays!

### ISSUE THREAD

**Issue by saiftheboss7** [chiefonboarding/ChiefOnboarding#246]
It’d be great if the Bot could automatically wish birthdays for each employee!

**Comment by GDay** [comment]
Interesting. I am not sure if this falls within the scope as it's an "onboarding' bot and birthday isn't a user field at the moment. But I am curious: how do you see this integrated; Just a message from the bot to the user? or a message to a channel where everyone can see/react to it as well?

**Comment by saiftheboss7** [comment]
Just a message to a channel, so others can wish him too 🙌

**Comment by GDay** [comment]
This has been added now. Thanks again for the suggestion!
