### ISSUE TITLE
Keycloak / OpenIdConnect login option

### ISSUE THREAD

**Issue by stereo9** [chiefonboarding/ChiefOnboarding#247]
in my organisation we are using keycloak to authenticate against all services.
i think it would be nice to be able to configure the login provider more dynamically, so SSO using keycloak would be possible with chiefonboarding

**Comment by GDay** [comment]
Yeah, this would be a great feature. Will add it to the backlog. Thanks for the suggestion.

**Comment by GDay** [comment]
@stereo9 OpenIDConnect is now supported! See: https://docs.chiefonboarding.com/deployment/#oidc-single-sign-on-sso
