### ISSUE TITLE
[Request] Remove Sequences from New Hires

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#250]
Hey @GDay 

It would be great if there was a way to remove a sequence thats been added to a new starter

Use case:

If you accidentally add the wrong sequence, which has happened more than my HR team like to admit, you can remove it and assign the correct one without duplications / doubling tasks

**Comment by GDay** [comment]
Yeah, good request. Thanks. I will add it to the backlog.

**Comment by GDay** [comment]
Will be merged when I have written tests for this: https://github.com/chiefonboarding/ChiefOnboarding/pull/252

Probably end of this week/early next week.
