### ISSUE TITLE
Adding Email Enviroment Settings

### ISSUE THREAD

**Issue by turbompGZ** [chiefonboarding/ChiefOnboarding#261]
Good day. Looking to configure environment settings for email. As we don't use slack or any other chat service. Took a look at issues page and there seems to be dead links to articles for integrating email. By chance could you provide some information on how to configure the environment variables for connecting to an email server? Not sure were to add setting for SMTP. Thanks in advance for any insight you can provide and happy holidays.

**Comment by GDay** [comment]
Hey! I think you are looking for this: https://docs.chiefonboarding.com/deployment/#email (scroll down a little for SMTP)

You are indeed correct that some of the links have gone bad. I changed the tool that builds the documentation. However, all documentation should be on this site: https://docs.chiefonboarding.com/

Happy holidays to you too!

**Comment by turbompGZ** [comment]
GDay. You are the man. Thank you for your time. I was able to configure SMTP perfectly. 

All the best!

**Comment by GDay** [comment]
Good to hear. Thanks for letting me know!
