### ISSUE TITLE
Azure Active Directory Issue

### ISSUE THREAD

**Issue by mbrewski** [chiefonboarding/ChiefOnboarding#264]
Can’t get a token. Keep receiving this error:

Couldn't save token: {"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'grant_type'.\r\nTrace ID: 8eb4206a-da95-48aa-8d7f-e42d25fe3c00\r\nCorrelation ID: d1076174-437a-40db-940d-b75ee9a52d54\r\nTimestamp: 2022-12-31 13:37:27Z","error_codes":[900144],"timestamp":"2022-12-31 13:37:27Z","trace_id":"8eb4206a-da95-48aa-8d7f-e42d25fe3c00","correlation_id":"d1076174-437a-40db-940d-b75ee9a52d54","error_uri":"https://login.microsoftonline.com/error?code=900144"}

I have the parameters all set and the request actually returns a token when using Postman. 

I’ve seen some responses to the error that the content type needs to be set to ‘x-www-form-urlencoded’ but can’t figure out how to set that in the manifest.

On another note: Any thoughts on where I can find useful information on creating the manifest?

**Comment by GDay** [comment]
This is weird, because the "grand_type" is provided. I will try to replicate it when I get the chance. 

The docs for the manifest can be found here: https://docs.chiefonboarding.com/integrations/

> I’ve seen some responses to the error that the content type needs to be set to ‘x-www-form-urlencoded’ but can’t figure out how to set that in the manifest.

`x-www-form-urlencoded` is already added through the `headers` part of the integration: https://integrations.chiefonboarding.com/manifest/5, so I don't think that's going to be the issue. Thanks for looking into it though!

**Comment by sabuto** [comment]
I am also getting this error

**Comment by vejadutoo** [comment]
@mbrewski or @GDay, Just wondering if any progress was made on figuring out that the issue was here. I finally decided to add AAD and I'm getting the same error.

```Couldn't save token: {"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'grant_type'[...]"error_uri":"https://login.microsoftonline.com/error?code=900144"}```

**Comment by GDay** [comment]
@vejadutoo I am quite busy right now, but I will try to take a look at this later this week.
It worked fine with I created the manifest, but perhaps something has changed in their API since then.

**Comment by vejadutoo** [comment]
Understood. Ill keep playing with it in the meantime. Also, thank you for all of the work you've put into this project. It really is a great fit for my use case.

**Comment by GDay** [comment]
Sorry for the slight delay on this. I have just fixed this issue. I have updated the config: https://integrations.chiefonboarding.com/manifest/5

If you are still have issues, then let me know.
