### ISSUE TITLE
Do not delete To Do item on Slack after Completing it 

### ISSUE THREAD

**Issue by dekadentno** [chiefonboarding/ChiefOnboarding#265]
I think it would be a nice feature to leave To Do items and not delete them after marking them as "Done" on Slack. 

**Current behaviour**: Onboardingbot sends an To Do item. You can check it with the "View Details" button, but after completing it with the "done" button, the user cannot go back to it again - the "I couldn't find any task" message appears.

**Wanted behaviour**: After completing an To Do item with the "done" button, the user should be able to check the completed To Do item again. It also looks confusing when the user completes multiple To Do items, as it cen be seen on the attached image:

![Screenshot at 2023-01-02 16-00-31](https://user-images.githubusercontent.com/12261635/210248394-b4d5d3c2-f766-4780-8918-c93592f980a4.png)

**Comment by GDay** [comment]
Agreed - thanks for the request. Will add it to backlog. If you need this quick, then please send me an email and I will create a quote for you to put this in the priority queue.

**Comment by dekadentno** [comment]
Thank you, email is on the way!
