### ISSUE TITLE
URL verification in slack fails

### ISSUE THREAD

**Issue by Kommu86** [chiefonboarding/ChiefOnboarding#266]
In my slack App I get following error:

settings.event_subscriptions.request_url URL isn’t verified. [Learn more](https://api.slack.com/events/url_verification)
https://onboarding.xxx/api/slack/bot —

The server is reachable from outside of the LAN - has the API be activated as described here:

https://docs.chiefonboarding.com/api/

Or is this really just neccessary to be able to create new hires and the Problem is located elsewhere?

**Comment by GDay** [comment]
You don't need the API for that. You only need the API if you want to create new hires from a third party application (not Slack). Check if this has been set up:

![image](https://user-images.githubusercontent.com/1939656/211919988-7fd916f3-2081-4678-8df1-508c75dd7077.png)

(the url is obviously different and also ignore the "socket mode" notification in the screenshot)

**Comment by Kommu86** [comment]
![grafik](https://user-images.githubusercontent.com/110096854/212018211-91d18961-43ad-4815-b17f-bb9b89356886.png)

The URL cannot be verified, while the server is reachable and I can login from outside the LAN. Posting messages to Slack is working. Is there anything on the server that needs to be configured additionally so that the URL is reachable?

**Comment by Kommu86** [comment]
The problem was resolved itself - we actually do not now why. But anway thanks for the help!
