### ISSUE TITLE
Missing template types

### ISSUE THREAD

**Issue by gituser317** [chiefonboarding/ChiefOnboarding#267]
Good day,

we have installed it via docker-compose.yml. The documentation says there are the following template types:
- To do items
- Resource items
- Introduction items
- Bade items
- Admin to do items
- Text/Slack/Email messages

On our fresh 2.0 install we only have
- To do
- Resources
- Introductions
- Appointments
- Preboarding
- Badges

Where can we find the admin to do items which are important for us?

**Comment by GDay** [comment]
Hi, you can find those items in the `sequences`. Sequences are basically a blueprint for your new hires. You can add admin tasks and text/slack/email messages in those and reuse them for any new hire you want. 

Let me know if you still have questions.

**Comment by vakninr** [comment]
Hi @GDay , I tried what you suggested here, but I could not create admin task from the sequences window. I can only see the existing tasks in the example provided and edit those. When I click the admin tasks on the right side and then create new task nothing happens. Also checking the html page, I couldn't find any action on the "create new one" seems like it doesn't suppose to do anything. 
Any other method to create an admin task?

Thanks

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/3775735/4bcb01dd-195e-4425-9d6f-8999fadeb528)

**Comment by GDay** [comment]
@vakninr try to drag the "Create new one" into any of the blocks in the sequence. When you "drop" it, it will allow you to create one.

**Comment by vakninr** [comment]
Thanks a lot, wasn't intuitive at all for me that it needed to be dragged first
