### ISSUE TITLE
New Hire Page Locale Issue

### ISSUE THREAD

**Issue by ad-stacc** [chiefonboarding/ChiefOnboarding#280]
Buddy & Manager is not translating, in any language selected

![image](https://user-images.githubusercontent.com/127509768/224386288-0888dec1-33f2-4039-95ea-699178c9577f.png)

![image](https://user-images.githubusercontent.com/127509768/224386373-ccdaf35f-66b9-4773-a601-9b43575245c3.png)

**Comment by GDay** [comment]
Thanks for letting me know. Will be fixed when I merge #281 (in the next few days).
