### ISSUE TITLE
Unable to find username and password ?

### ISSUE THREAD

**Issue by 20972097** [chiefonboarding/ChiefOnboarding#282]
Hi ,

Just installed this, Using the Docker install method on a local server with Caddy .

All is good and i get to the login page fine. But unable to find any type of password and username in the logs as the guide dictates ?

I am looking in the docker container logs ? is that where i should be looking ?

I have also tried specifying the variables in the docker compose YML using ACCOUNT_EMAIL and ACCOUNT_PASSWORD , But does not seem to work ? i still cannot login .

Is there an easier way to see if this is working ? or to get the username and password.

Thanks
Luke

**Comment by 20972097** [comment]
Please disregard this,

I hadnt set the ACCOUNT_EMAIL and ACCOUNT_PASSWORD before running compose .

I thought i had removed all the instances when i ran it again, seems i didnt delete the volumes.

I can now login with the username and password specified in the docker file

**Comment by GDay** [comment]
Related to: #254

I have planned to add an initial setup page to the application, that should resolve these issues. Glad you got it sorted!

**Comment by GDay** [comment]
When I merge #284 (in the next few days), the account/password environment variables option will be gone. It will show a page to setup the initial organization and account when there is none yet.

**Comment by 20972097** [comment]
Thank you for the reply GDay,

Regarding email setup and adding a SMTP server, is there any additional steps required with docker ?

We have a inhouse SMTP server , I have added the required SMTP settings into the docker compose yml file

It just doesnt do nothing , just goes to a blank page. ( Sending a forgot password email )

What is Chiefonboarding using to connect to the SMTP server ? 

Any way to test these settings ?

Sorry for my ignorance i'm not overly familiar with docker or linux sendmail,postfix

I used the code from

https://github.com/chiefonboarding/Documentation/blob/main/integrations/Email.md

Thanks
Luke !

**Comment by GDay** [comment]
You can send test mails if you go setttings -> welcome messages:
![image](https://user-images.githubusercontent.com/1939656/225029646-7d6860ef-8ff1-460a-8651-47655d0eefdc.png)

That's old documentation that you are referring to. You should be following this: https://docs.chiefonboarding.com/deployment/#email

In particular, see this note: 

> For SMTP, you only need to set either EMAIL_USE_TLS OR EMAIL_USE_SSL to True. If you set both, then it will likely not send out any emails.

If you are still having issues, then try this:

First check the name of the docker container:

```
docker ps
```

Open Django shell by going into the docker container (I am using `chiefonboarding_web` as the docker name here, change it with whatever you have):

```
docker exec -it chiefonboarding_web python manage.py shell
```
Sending email manually (change email address to where you want this test email to go):

```
from django.conf import settings
from django.core.mail import send_mail

send_mail("Test subject", "Test message", settings.DEFAULT_FROM_EMAIL, ["hello@chiefonboarding.com"])
```

It should post an error if something is misconfigured.

**Comment by 20972097** [comment]
Thank you that helped a lot in finding the problem . Now working fine ;)

Just to note : Unsure if this is documented but if you are running into a problem running this locally with a local SSL Certificate that is auto generated you need to add this to the CaddyFile

tls internal

Otherwise you cant bypass the SSL certificate error.
