### ISSUE TITLE
How to use local storage?

### ISSUE THREAD

**Issue by satoshinotdead** [chiefonboarding/ChiefOnboarding#283]
We have mounted our storage data within the same hosting provider so how can we use local data instead S3 or similar one?

**Comment by GDay** [comment]
Local storage is currently not supported. The only way to achieve what you want is to use a minio server, which is described in this section: https://docs.chiefonboarding.com/deployment/#object-storage-updownloading-files (scroll down a bit). With that, you can set up the minio server on the same server that ChiefOnboarding is running.
