### ISSUE TITLE
Error when creating new department in New Hire form

### ISSUE THREAD

**Issue by Knowaaaa** [chiefonboarding/ChiefOnboarding#286]
When creating a new hire and adding a new department, we are always greeted with "Select a valid choice. That choice is not one of the available choices". Do we need to add object storage in order for this feature to work? We've found a workaround by just leaving the department box blank, but that isn't really a permanent solution.

**Comment by GDay** [comment]
Thanks for reporting this issue! You are indeed correct, that didn't work correctly, but I have just pushed a fixed that resolves this issue.
