### ISSUE TITLE
Test messages not working

### ISSUE THREAD

**Issue by oascout25** [chiefonboarding/ChiefOnboarding#289]
I'm working on setting up a new deployment and was using the "Send test message" button from settings/welcome_message to test if I had configured SMTP variables correctly. Which consistently returned:

"POST /admin/settings/welcome_message/en/0/test_message/ HTTP/1.1" 500 145 "https://<domain.name>/admin/settings/welcome_message/en/0/"

Eventually, I was poking around in the container files and couldn't find the path being called, I wonder if that was causing the 500 error. After that, I tried setting up a new admin, and it successfully sent credential emails, although the "send test message" still kicked out a 500 error.

**Comment by ismnilsonzegarra** [comment]
Hi i'm having the same issue, but the only test message that really works is the second one, the "Welcome to new hire", but the another ones fails, in the browser debugger i see in the other tabs this error:

Error: <svg> attribute viewBox: Expected number, "0 0 100% 4". in content.js 2

I'm using the interface in Spanish and tested in English and deustch and the same issue.

**Comment by GDay** [comment]
@ismnilsonzegarra very strange, the error in the browser debugger is likely not related to ChiefOnboarding, but to a extension that you are using in the browser. ChiefOnboarding does not have a `content.js` file.

The `Pre-Boarding` and `New Hire Welcome` are emails, the `Text Welcome` is a text message and the `Slack Welcome` and
`Slack Knowledge` are Slack messages. For the text message and the Slack messages to work, you need to have these setup and your user needs to be connected to Slack and have a phone number. 
Can you elaborate on what does not work for you and if you have those set up? Also what error message do you get (if any)?

**Comment by ismnilsonzegarra** [comment]
Hi, thanks for the advise, i was trying in Microsoft edge, change to Firefox and now this is the behavior:

![steps to reproduce error](https://i.imgur.com/IdtauvL.gif)

As you see the second options waits seconds and return 200, but the first one return 500 error.

**Comment by GDay** [comment]
@ismnilsonzegarra Thanks a lot for that video. This happens to be a bug that was introduced when I added the setup wizzard. This also resulted in finding a security issue (see PR #293 for the full details). You should update your instance and then sending test emails should work fine!

Thanks again!
