### ISSUE TITLE
Example to integration to Office365 login

### ISSUE THREAD

**Issue by joenilson** [chiefonboarding/ChiefOnboarding#294]
Hi, i need to add Office365 Login but i don't see where to get documentation about the manifest for it, there is a way to do that, 

I want to do a Keycloak integration later, but now i need to integrate directly with O365, where i could get the documentation.

PS. my other github is @ismnilsonzegarra, this is my opensource login.

**Comment by GDay** [comment]
The manifests for integrations are in place to create accounts (or trigger other things) based on actions/time from a new hire. You are not able to create a manifest for logging users in. We would have to code that, to make that happen. 

Currently, Google is supported. When PR https://github.com/chiefonboarding/ChiefOnboarding/pull/291 gets merged, you will be able to use OpenID to log users in, it looks like Microsoft supports that:  https://learn.microsoft.com/nl-nl/azure/active-directory/develop/v2-protocols-oidc. So I think that could work.

**Comment by GDay** [comment]
The PR has been merged, so this should be possible now. Let me know if you are having any issues.
