### ISSUE TITLE
Progress bar in onboarding sequence only showed in english

### ISSUE THREAD

**Issue by joenilson** [chiefonboarding/ChiefOnboarding#299]
When we assign a sequence to a new hire and the admin uses the interface in other language rather than english the progress bar graph is not showed, it keeps as a gray bar.

![](https://i.imgur.com/KLgPdBU.gif)

**Comment by GDay** [comment]
Thanks for reporting that. This is an interesting bug:

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/1939656/a8a77f04-d28a-446a-96fe-587f2e84e199)
![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/1939656/ac99505e-8780-4500-a57c-919d6930c0a6)

Looks like the localization changes the dot notation (`.` and `,`). The `,` won't be rendered. Rounding it to a full number would likely be the easiest solution (doesn't have to be super accurate anyway). Will take a look later this week.

**Comment by joenilson** [comment]
Thanks, i'm doing extensive tests before running on production.

**Comment by GDay** [comment]
Thanks. I have just fixed it in #300.
