### ISSUE TITLE
Error accessing from browser

### ISSUE THREAD

**Issue by jharjadi** [chiefonboarding/ChiefOnboarding#3]
Hello 
Finally successful installation with no errors but encountered this issue when access it from browser, would you care to shed the light please?

Many thanks 
Jim

![image](https://user-images.githubusercontent.com/819854/87917235-fff08480-cab7-11ea-9316-710762f40ad3.png)

**Comment by GDay** [comment]
Hey Jim, Looks like either collectstatic hasn't ran (try to run `docker-compose run web python manage.py collectstatic --clear --noinput`) or something got misconfigured through the domain. Check if the URL of those files matches your domain name. 

Also, someone is working on an improved way of installing this on a VPS (with let's encrypt, etc), see the pull request (still work in progress, not fully functional) #1 . So perhaps wait a day or two until we got the bugs out of the pull request and merged it.

**Comment by GDay** [comment]
@jharjadi Feel free to try the new version. I just merged the #1 into master and deployment should be super easy now to deploy (including Let's Encrypt certificate). Feel free to open a new issue if you are still having issues with installing it.
