### ISSUE TITLE
integration manifest problem with choice with items

### ISSUE THREAD

**Issue by joenilson** [chiefonboarding/ChiefOnboarding#301]
Trying to create a manifest with a form with fixed array of choices i get an error:

The manifest is:

```
{
	"form": [{
            "id": "companyId",
            "name": "Select Company to add user to",
            "type": "choice",
            "items": [
                { "id": "233", "name": "option 1" },
                { "id": "234", "name": "option 2" }
            ],
            "choice_value": "name"
        }
    ],
}
```

The error in the update integration's screen is: {"form": [{"items": ["Not a valid string."]}]}

**Comment by GDay** [comment]
Thanks for reporting this. It's a known issue and will be fixed soon: https://github.com/chiefonboarding/ChiefOnboarding/issues/292
I am almost done reviewing the PR that includes this fix.
