### ISSUE TITLE
unable to show a video embed from url

### ISSUE THREAD

**Issue by joenilson** [chiefonboarding/ChiefOnboarding#305]
When creating a resource type course we need to add a video url for the onboarding process

The rich text editor allows put an image or a link, while the admin is creating the content and add a video url the preview is showed as this picture:

![Imgur](https://i.imgur.com/kZcxrYA.png)

But when the new hire receive the content it's only displayed as text:

![Imgur](https://i.imgur.com/Pbcf6Qh.png)

There is a way to show the video in a proper way?.

**Comment by joenilson** [comment]
Actually, looking into the code i see that system use codex-editor, they have an [embed plugin](https://github.com/editor-js/embed), could it be  useful to get this functionality.

**Comment by GDay** [comment]
The embed plugin is already installed: https://github.com/chiefonboarding/ChiefOnboarding/blob/801198fa5a3ade22a75b35deb3e26d703cd2de83/back/users/templates/admin_base.html#L326-L334

Looks like I only forgot to render it here: 
https://github.com/chiefonboarding/ChiefOnboarding/blob/master/back/new_hire/templates/_content.html

It needs another `if` block there to show the embed block:

Example output from the editor (youtube and paragraph block):

```
{
   "time":1683928465759,
   "blocks":[
      {
         "id":"8RgP494Lcs",
         "data":{
            "embed":"https://www.youtube.com/embed/06NdrxCDw04",
            "width":580,
            "height":320,
            "source":"https://www.youtube.com/watch?v=06NdrxCDw04",
            "caption":"",
            "service":"youtube"
         },
         "type":"embed"
      },
      {
         "id":"KfJ26MVrBo",
         "data":{
            "text":"test"
         },
         "type":"paragraph"
      }
   ],
   "version":"2.25.0"
}
```

By the way, you should use the normal url, not the embed youtube url when pasting it in the editor.

Won't have much time in the next few days but will get this fixed later this week. I would also welcome a PR for this though, shouldn't be too hard.

**Comment by joenilson** [comment]
Thanks for the information, writing the PR.

When the docker image will be updated with the latest changes?.

**Comment by GDay** [comment]
> When the docker image will be updated with the latest changes?.

Should be up in a few minutes.

**Comment by joenilson** [comment]
Added embed if and fixed a bug with block.data.file.extension, the correct variable is block.data.file.ext. PR #306

**Comment by GDay** [comment]
Thanks. This should be fixed now.
