### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by TaoChan1005** [chiefonboarding/ChiefOnboarding#319]
Master branch. I met this problem: I try to change ALLOWED_HOSTS=* into ALLOWED_HOSTS={MY_HOST}, but it stiil doesn't work.

Forbidden (403)
CSRF verification failed. Request aborted.

Help
Reason given for failure:

    Origin checking failed - https://test.xxxx.com does not match any trusted origins.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/4.2/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:

Your browser is accepting cookies.

- The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
- In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
- If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
- The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
- You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.

<img width="1249" alt="image" src="https://github.com/chiefonboarding/ChiefOnboarding/assets/42793494/72ad32d1-da8b-4eb3-82c2-cf924cf7628c">
<img width="1198" alt="image" src="https://github.com/chiefonboarding/ChiefOnboarding/assets/42793494/36b2d64d-0454-426d-b802-8d2c279f2989">

**Comment by GDay** [comment]
Weird. A few questions:
- Is that site on `https`? 
- It looks like you are using Django debug bar on that test site, is that correct? 
- Have you disabled the setting "DEBUG"?

**Comment by TaoChan1005** [comment]
- [x] Is that site on https?
Yes, I use apache2 as reverse proxy
```apache2
<VirtualHost *:443>
    ServerName  test.xxxxx.com
    SSLEngine on
    SSLProxyEngine On
    # SSLProxyVerify none
    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /(.*) ws://localhost:15073/$1  [P,L]
    <Location />
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}  
        RequestHeader set Host %{HTTP_HOST}e
        ProxyPass http://localhost:15073/
        ProxyPassReverse http://localhost:15073/
    </Location>    
</VirtualHost>
```
- [ x] It looks like you are using Django debug bar on that test site, is that correct?
Yes.
- [X ] Have you disabled the setting "DEBUG"?
I tried. but it still doesn't work.


Output
```
test-web-1  | Forbidden (Origin checking failed - https://test.xxxx.com does not match any trusted origins.): /
```

**Comment by GDay** [comment]
Thanks for the details!

Are you running this in Docker? Then you might need to do this: https://www.alansiu.net/2023/02/24/origin-checking-failed-does-not-match-any-trusted-origins-csrf-errors-in-crypt-server/

**Comment by TaoChan1005** [comment]
Yes, I run it in docker. i try 
```
ALLOWED_HOSTS=https://test.xxx.com
# ALLOWED_HOSTS=test.xxx.com
CSRF_TRUSTED_ORIGINS='https://test.xxxx.com'
# CSRF_TRUSTED_ORIGINS=https://test.xxxx.com
```
it doesn't work. 

I can login though OIDC, but I can not use/update any form

**Comment by GDay** [comment]
Could you try to add it as a list instead? 
See: https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins

So, for example:
CSRF_TRUSTED_ORIGINS=['https://test.xxxx.com',]

**Comment by TaoChan1005** [comment]
it works.  I set env:
```
CSRF_TRUSTED_ORIGINS=https://test.xxxx.com
```
and and this into `setting.py`

```python
if env("CSRF_TRUSTED_ORIGINS", default="") != "":
    CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS").split(",")
else:
    CSRF_TRUSTED_ORIGINS = []
```

Maybe, we can check  ALLOW_HOST or BASE_URL, then add 'it' into CSRF_TRUSTED_ORIGINS automatically

**Comment by GDay** [comment]
Yeah, that would be great. Will add it to my list of things to do. Thanks a lot for digging into this!

**Comment by TaoChan1005** [comment]
i notice there is a setting:
```python
CORS_ALLOWED_ORIGINS = [
    origin for origin in env.list("CORS_ALLOWED_ORIGINS", default="")
]
```
what's this? I try use CORS_ALLOWED_ORIGINS, but it doesn't work

**Comment by TaoChan1005** [comment]
sorry, 'CSRF_TRUSTED_ORIGINS' and 'CORS_ALLOWED_ORIGINS' confused me

**Comment by GDay** [comment]
Yeah, it's a different setting.

Having said that, it's an undocumented setting and I think it's some legacy/dead code that came from when ChiefOnboarding was a decoupled VueJS/Django application. VueJS could live on a different server, which would then need the CORS_ALLOWED_ORIGINS to be able to communicate between each other.

I think this setting (and package) related to it can be removed entirely. The setting comes from this package: https://github.com/adamchainz/django-cors-headers 

Will look into it later next week. Thanks!

**Comment by GDay** [comment]
I have set the `BASE_URL` as the default and removed that other package.
