### ISSUE TITLE
OIDC Role mapping with Azure registration app

### ISSUE THREAD

**Issue by vakninr** [chiefonboarding/ChiefOnboarding#324]
Hi,
I was trying to connect the OIDC feature with Azure Registration app (I've done it successfully and logged in to the system).
The issue was when I was trying to map the roles.

After overviewing the code a bit I noticed that the roles are taken from the userinfo endpoint. (In you example with CAS system I guess you can add those claims and use it) but when using Microsoft endpoint the userinfo claims are fixed. More info here: https://learn.microsoft.com/en-us/azure/active-directory/develop/userinfo

The way that Microsoft suggest to take it is to use the ID Token JWT (which is superior to the userinfo endpoint) and take it from the claims  there (which I do see in my ID Token JWT).

Not sure if this is a feature request or bug, but role mapping seems to not work with Microsoft OIDC.

Thanks

**Comment by GDay** [comment]
Interesting case. I think most OIDC providers do use the userinfo endpoint to fetch additional data, but it's not standardized, so it can vary. 

It should be relatively easy to make this compatible with the Azure one. We would need an extra environment setting to toggle this on and then decode the JWT (which we already save in the session) to use to extract the role from.

**Comment by vakninr** [comment]
@GDay - I'm not sure additional setting will be required, since OIDC provide the ID Token once you do the authorize API (which needed to be called before anyway), The role mapping can just have a fallback to the ID Token in case it is not found in the User Info API. I created a PR with the changes....

**Comment by GDay** [comment]
>  I'm not sure additional setting will be required

Not necessarily required, but I had a setting in mind to not call the userinfo endpoint if we were expecting the groups to be part of the token. I think we can get the firstname/lastname etc also from the token, so in that case, the userinfo endpoint would be pretty pointless to call. 

It's not a big deal and it's fine how it is. I might add that setting at some point.

Thanks again for the PR!
