### ISSUE TITLE
How to Debug Integrations?

### ISSUE THREAD

**Issue by Dan6erbond** [chiefonboarding/ChiefOnboarding#329]
I have an integration I created for Authentik that's similar to the others found on https://integrations.chiefonboarding.com/. The problem is, that the app behaves as if everything is working as it should, but Authentik's API shows no logs of being accessed, and CO's logs don't show any errors/warnings/infos either. It's hard to see what didn't work without logging.

The integration's form also doesn't seem to be considering the `GROUP_ID` field that I want.

My integration's manifest:

```json
{
    "form": [
        {
            "id": "GROUP_ID",
            "url": "/api/v3/core/groups/",
            "name": "Select group to add user to",
            "type": "choice",
            "data_from": "results",
            "choice_name": "name",
            "choice_value": "pk"
        }
    ],
    "exists": {
        "url": "/api/v3/core/users/?email={{email}}",
        "method": "GET",
        "expected": "{{email}}"
    },
    "execute": [
        {
            "url": "/api/v3/core/users",
            "data": {
                "name": "{{first_name}} {{last_name}}",
                "email": "{{email}}",
                "groups": [
                    "{{GROUP_ID}}"
                ],
                "username": "{{first_name}} {{last_name}}"
            },
            "method": "POST"
        }
    ],
    "headers": {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": "Bearer {{TOKEN}}"
    },
    "initial_data_form": [
        {
            "id": "TOKEN",
            "name": "Please put your token here",
            "description": "You can find your token here: https://...."
        }
    ]
}
```

**Comment by GDay** [comment]
Debugging is definitely a bit harder with these integrations, I will have to fix that.

When you create an account for a user (through people -> new hires -> select a new hire -> access) it will show the error when it fails. 

You have paths as the `url`, but those should all be the full url (including domain name, protocol etc). Otherwise it doesn't really know where to send the request to. 

> The integration's form also doesn't seem to be considering the GROUP_ID field that I want.

Not sure what you mean by that. The integration looks fine to me!

**Comment by Dan6erbond** [comment]
Thanks for your quick responses!

> When you create an account for a user (through people -> new hires -> select a new hire -> access) it will show the error when it fails.

Unfortunately I wasn't getting any errors, and then checking Authentik later I saw that it wasn't including the headers until I added them to the `execute` action directly.

> You have paths as the url, but those should all be the full url (including domain name, protocol etc). Otherwise it doesn't really know where to send the request to.

I just removed the host for sensitivity reasons. In my integration they're all there, and in the integration I posted to [[integrations.chiefonboarding.com]()](https://integrations.chiefonboarding.com/) I created a host var.

> Not sure what you mean by that. The integration looks fine to me!

It turns out the `method` was missing from the form field to consider it valid, now I'm able to select groups at least!

**Comment by GDay** [comment]
> Unfortunately I wasn't getting any errors, and then checking Authentik later I saw that it wasn't including the headers until I added them to the execute action directly.

I doubt that's correct. See this (recently tested) manifest for example: https://integrations.chiefonboarding.com/manifest/6. It doesn't have `headers` in the `execute` part and it works. Whatever is in the main `headers` will be used for all requests, unless you overwrite them in the other parts.

> In my integration they're all there, and in the integration I posted to https://integrations.chiefonboarding.com/

Thanks for posting it. Appreciate that! In the post, you had hardcoded your auth urls, I have now replaced them with the `{{HOST}}` variable to avoid doxxing yourself.

> It turns out the method was missing from the form field to consider it valid, now I'm able to select groups at least!

Yeah, the default is `POST` for all requests. If you need a different method, then you can overwrite it. I should clarify that in the docs. Glad to hear that you figured it out.

**Comment by GDay** [comment]
Closing this as I have implemented:
1. An integration tracker (it keeps track of the requests being made): https://github.com/chiefonboarding/ChiefOnboarding/pull/401
2. A live manifest builder/tester: https://github.com/chiefonboarding/ChiefOnboarding/pull/417

That should make it significantly easier to create, debug and test integrations.
