### ISSUE TITLE
Migrations are not run during initial setup 

### ISSUE THREAD

**Issue by mangatinanda** [chiefonboarding/ChiefOnboarding#34]
I see `RUN python manage.py migrate` is commented in back/Dockerfile. Is this intentional? If so, documentation needs to be updated to run `docker-compose run web python3 manage.py migrate`

**Comment by GDay** [comment]
Thanks! I think I had issues with migrating at some point and then commented that line. I have added the extra instructions with this commit: https://github.com/chiefonboarding/Documentation/commit/ec9c2843218032789a8985ffcfc4eb9998555bb8

Thanks again for letting me know!
