### ISSUE TITLE
Item edit window closes when dropdown is clicked outside the window

### ISSUE THREAD

**Issue by helgio** [chiefonboarding/ChiefOnboarding#345]
When you are editing an item and selecting someone in the "For" drop-down, it closes the window if the drop-down exceeds the window. All the work is unsaved so this can be very annoying.

![Animation](https://github.com/chiefonboarding/ChiefOnboarding/assets/16520386/a1e56a74-cf1d-4f52-9c1f-1df6ed8b57c2)

**Comment by GDay** [comment]
Thanks for the report. This is indeed a very annoying bug. It might be best to just disable the outside clicking of the modal completely, this would then also avoid accidentally clicking outside and losing all changes.

**Comment by GDay** [comment]
Fixed now! Thanks again for letting me know!
