### ISSUE TITLE
Subitems in numbered list do not appear in final copy

### ISSUE THREAD

**Issue by skorvek** [chiefonboarding/ChiefOnboarding#377]
See attached screenshots.

Text such as this only shows the top-level list item, not the sub item.

1. Item
1.1. Subitem  
2. Item
2.1 Subitem

<img width="869" alt="Screenshot 2023-10-18 at 1 31 04 PM" src="https://github.com/chiefonboarding/ChiefOnboarding/assets/11871683/d08f50f4-167c-4e88-9f80-2f4143265f7e">
<img width="867" alt="Screenshot 2023-10-18 at 1 31 41 PM" src="https://github.com/chiefonboarding/ChiefOnboarding/assets/11871683/16cd60e5-f107-4738-aa06-b213fa2d292c">

**Comment by GDay** [comment]
Sorry about that. Not sure how I missed that, but you can now have multiple deeper levels. Please note that it will just start counting from 1 again, so like this: 
![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/1939656/a830965a-6ced-4cfa-8ff7-f969ce02fb77)

I have not implemented the sub counting for now as I have a lot more on my plate that I need to get done.
