### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by amolvishwakarma** [chiefonboarding/ChiefOnboarding#40]
Chiefonboarding docker application is running and up which has been done proxy through nginx on ssl able to see the frontend screen but login not working with the user that has created earlier and in developer console error shows 400 bad request for api post login

**Comment by GDay** [comment]
Generally, a 400 error means that Django doesn't recognize the `ALLOWED_HOSTS`. Can you check if the `ALLOWED_HOST` variable is set to your URL in the Django environment variables? That's in `back/back/.env`.

**Comment by amolvishwakarma** [comment]
> 
> 
> Generally, a 400 error means that Django doesn't recognize the `ALLOWED_HOSTS`. Can you check if the `ALLOWED_HOST` variable is set to your URL in the Django environment variables? That's in `back/back/.env`.

Allowed host value is '*' in `back/back/.env` @GDay

**Comment by GDay** [comment]
Oh wait, I think I misread your first message. Sorry. The login part loads, but you just cannot login, is that correct?

A 400 error in that case means that your username and password are not correct. Please note that the username (which needs to be an email address) and password are both case-sensitive. Also make sure that you didn't add a space after your username.

**Comment by amolvishwakarma** [comment]
> Oh wait, I think I misread your first message. Sorry. The login part loads, but you just cannot login, is that correct?
> 
> A 400 error in that case means that your username and password are not correct. Please note that the username (which needs to be an email address) and password are both case-sensitive. Also make sure that you didn't add a space after your username.

Email address and password both are correct created another user with same password and same error for that too @GDay

**Comment by GDay** [comment]
Very strange. Were you able to log in previously or have you never been able to log in? When you make the login request, what does it respond with? When I type in a wrong username and password, it responds with this:

![Schermafbeelding 2021-03-04 om 14 24 36](https://user-images.githubusercontent.com/1939656/109970564-7fecf700-7cf5-11eb-9dff-1ee5985698ae.png)

**Comment by amolvishwakarma** [comment]
> Very strange. Were you able to log in previously or have you never been able to log in? When you make the login request, what does it respond with? When I type in a wrong username and password, it responds with this:
> 
> ![Schermafbeelding 2021-03-04 om 14 24 36](https://user-images.githubusercontent.com/1939656/109970564-7fecf700-7cf5-11eb-9dff-1ee5985698ae.png)

Not been able to login @GDay

**Comment by GDay** [comment]
When you make the login request, what does it respond with? Rightmouseclick on the screen -> inspect element -> open the network tab -> make the login request and then click on 'response'. Does it give the same error that I showed in the screenshot?

**Comment by amolvishwakarma** [comment]
> 
> 
> When you make the login request, what does it respond with? Rightmouseclick on the screen -> inspect element -> open the network tab -> make the login request and then click on 'response'. Does it give the same error that I showed in the screenshot?

![image](https://user-images.githubusercontent.com/57523705/109972532-6c558680-7d1d-11eb-8151-166dba6e695a.png)

Error msg is username and password do not match please try again same as yours @GDay

**Comment by GDay** [comment]
Okay, so yeah, your username and password are probably not correct.  Let's try this, just to be sure:

When you have SSH access, do this: 
```
docker-compose run web python3 manage.py shell
```
Then do this:
```
from django.contrib.auth import get_user_model
list(get_user_model().objects.all().values_list('email', flat=True))
```
That should give you a list with users that are in the system right now. Then do this:

```
def reset_password(u, password):
    try:
        user = get_user_model().objects.get(username=u)
    except:
        return "User could not be found"
    user.set_password(password)
    user.save()
    return "Password has been changed successfully"
```
That adds a function that we can use to change the password.

Up next, we will change the password. Do the following, but change `username` with any of the values that are shown in the list and then `password` with something super easy. Avoid using special characters in this case. We just want to get logging in working right now. You should change it once you are logged in to something that is more complicated.
```
reset_password(username, password)
```
By the way, you might want to remove the screenshot as it shows your domain name.

**Comment by amolvishwakarma** [comment]
![image](https://user-images.githubusercontent.com/57523705/109974657-c9523c00-7d1f-11eb-866d-b86997d39680.png)
Am i doing mistake somewhere please check this @GDay

**Comment by amolvishwakarma** [comment]
This function code doesn't allowing me to change password @GDay

**Comment by GDay** [comment]
I think I see where it went wrong. So.. when creating a user, it says on the page to do 
```
User.objects.create_admin("<first name>", "<last name>", "<email>", "<password>")
```
You probably included the `<` `>`. That's not correct. Here is an actual example of adding a new user:
```
User.objects.create_admin("Stan", "Doe", "hello@chiefonboarding.com", "Somethingsupersecret")
``` 

So please remove your users:
```
get_user_model().objects.all().delete()
```
and add a new user again but then don't use `<` and `>`. 

Makes sense?

**Comment by amolvishwakarma** [comment]
> 
> 
> I think I see where it went wrong. So.. when creating a user, it says on the page to do
> 
> ```
> User.objects.create_admin("<first name>", "<last name>", "<email>", "<password>")
> ```
> 
> You probably included the `<` `>`. That's not correct. Here is an actual example of adding a new user:
> 
> ```
> User.objects.create_admin("Stan", "Doe", "hello@chiefonboarding.com", "Somethingsupersecret")
> ```
> 
> So please remove your users:
> 
> ```
> get_user_model().objects.all().delete()
> ```
> 
> and add a new user again but then don't use `<` and `>`.
> 
> Makes sense?

Yes , I had used < > while creating user , I will remove users and create one and let you know if the issue will resolve  @GDay

**Comment by amolvishwakarma** [comment]
Yes, it worked 
Thanks for your help and support it worked like a charm and sorry for the trouble you can close the issue @GDay

**Comment by GDay** [comment]
Awesome, good to hear! No worries - happy to help. I will update the docs to make it a bit clearer.

**Comment by thealpha93** [comment]
I had to user `email` instead of username to reset password
```
def reset_password(mail, password):
    try:
        user = get_user_model().objects.get(email=mail)
    except:
        return "User could not be found"
    user.set_password(password)
    user.save()
    return "Password has been changed successfully"
```
