### ISSUE TITLE
Render - Setup - CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by JonasMe** [chiefonboarding/ChiefOnboarding#402]
Hi,

**Are you on the latest version of ChiefOnboarding? We only give support for version 2.x.**
Deployed from "Render" button on website using master branch

**What browser are you using?**
Chrome and Edge

**What did you do?**
Deployed to render.com ref. documentation. Filled out the "Setup" form and clicked Submit
![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/3063806/80c1af88-2480-4517-ba1b-2aa501d4502f)

**What did you expect to see?**
The setup to complete and possibility to utilize ChiefOnboarding

**What did you see instead?**
CSRF Verification failed screen
![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/3063806/c782816f-b727-4d06-bd91-978aa061a9d4)

**Utilizing https?**
Yes default through Render
![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/3063806/5edd3227-9da7-4d5d-8b4b-1accd052ba77)

Looking much forward to hearing from you :) Thanks in advance

**Comment by GDay** [comment]
Hey, I just deployed one myself on Render and it seems to work fine for me. Can you check that the "ALLOWED_HOSTS" (environment variable) is the same as your domain name (without the `https://`. For me, I have entered `choiefonboarding.onrender.com`, but yours should be slightly different.

**Comment by JonasMe** [comment]
Thanks for responding.
Something is definitely up with the ALLOWED_HOSTS enviornmental variable. I've added multiple entries to the list, and now after seeing your message, i've removed all but the onrender url, and now it seems to work.

Thanks a lot for replying
