### ISSUE TITLE
Chiefonboarding app.js taking too much time too load 

### ISSUE THREAD

**Issue by amolvishwakarma** [chiefonboarding/ChiefOnboarding#41]
Nginx proxy taking too much time to load app.js max time consumes 1.6 min seen in network tab @GDay

**Comment by GDay** [comment]
It's weird, I don't have `app.js`. I do have one JavaScript file that is fairly large (2.45MB). Is that the file that is causing problems for you?

![image](https://user-images.githubusercontent.com/1939656/110123015-ad52a700-7dc0-11eb-8836-ca2677da3c78.png)

For me, it loads in 500ms, but I can imagine that for some people, with lower internet speed, it might take longer. 

One way to fix this, would be to change the timeout on NGINX. Gunicorn might have a limit too, but I am not sure. For NGINX, adding this to the config file should work:
```
    fastcgi_buffers 8 16k;
    fastcgi_buffer_size 32k;
    fastcgi_connect_timeout 90s;
    fastcgi_send_timeout 90s;
    fastcgi_read_timeout 90s;
    proxy_read_timeout 90s;
```
Though, that's treating the symptom and not the cause. I will see if I can make that file smaller.

**Comment by GDay** [comment]
Oh, you closed the issue. Did you resolve this?

**Comment by amolvishwakarma** [comment]
> 
> 
> It's weird, I don't have `app.js`. I do have one JavaScript file that is fairly large (2.45MB). Is that the file that is causing problems for you?
> 
> ![image](https://user-images.githubusercontent.com/1939656/110123015-ad52a700-7dc0-11eb-8836-ca2677da3c78.png)
> 
> For me, it loads in 500ms, but I can imagine that for some people, with lower internet speed, it might take longer.
> 
> One way to fix this, would be to change the timeout on NGINX. Gunicorn might have a limit too, but I am not sure. For NGINX, adding this to the config file should work:
> 
> ```
>     fastcgi_buffers 8 16k;
>     fastcgi_buffer_size 32k;
>     fastcgi_connect_timeout 90s;
>     fastcgi_send_timeout 90s;
>     fastcgi_read_timeout 90s;
>     proxy_read_timeout 90s;
> ```
> 
> Though, that's treating the symptom and not the cause. I will see if I can make that file smaller.

Thanks , I have added gzip compresion will try this too and check the result @GDay

**Comment by amolvishwakarma** [comment]
> 
> 
> Oh, you closed the issue. Did you resolve this?

Closed because it is better than before after adding gzip compression @GDay 

In nginx: Added these lines 

# gzip
  gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript application/x-javascript;
  gzip on;

**Comment by GDay** [comment]
Oh, right. Thanks for letting me know. Gzip will indeed help quite a bit. I will still reopen this as I want to make the javascript file smaller. 2MB for just that one javascript file is too big. There must be something that I can strip out to make that smaller.
