### ISSUE TITLE
Conditional Blocks - Based on one or more to do item(s)

### ISSUE THREAD

**Issue by SHammoud** [chiefonboarding/ChiefOnboarding#416]
This does not seem to be able to see the items created.

I have added this:

<img width="802" alt="image" src="https://github.com/chiefonboarding/ChiefOnboarding/assets/1060597/ae5a75ba-2fd0-4abc-a1fd-da1958a2fd88">

But this is not available when adding a new block:

<img width="1179" alt="image" src="https://github.com/chiefonboarding/ChiefOnboarding/assets/1060597/00442c8d-1f7f-4ee6-aa55-03c06a571eae">

Am I missing something?

**Comment by GDay** [comment]
That block only works with templates, not with custom items. So you would have to create a to do item in the templates section and then you can select it there.
It's not super well documented, so I get why you are confused.

Hope this helps.
