### ISSUE TITLE
only 1 image is loaded

### ISSUE THREAD

**Issue by reiniertc** [chiefonboarding/ChiefOnboarding#431]
When I look at the page with Collegues, the profile images are wrong. 
In stead of loading the profile pictures of each collegue, it shows the picture of the person who is logged in. 

It's the case if logged in as administrator, and also if I login as the new hire. 

(I use Minio as object store)

**Comment by GDay** [comment]
That's a bug! Thanks for the report. I have created a fix for this (waiting for CI and will then merge)

**Comment by GDay** [comment]
Fixed. Pull down latest docker image and it should be working correctly now.

**Comment by reiniertc** [comment]
Check: it works now. Thanks a million @GDay
