### ISSUE TITLE
I can't log in and can't enter the main page of the system.

### ISSUE THREAD

**Issue by admin10101010** [chiefonboarding/ChiefOnboarding#446]
Using the following template, both the specified version and the test are the result of consent.
After initializing the account setup, the cycle redirects to the login screen.

version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chiefonboarding
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    image: chiefonboarding/chiefonboarding:v2.0.62
    restart: always
    ports:
      - "8888:8000"
    environment:
      - SECRET_KEY=somethingsupersecret
      - DATABASE_URL=postgres://postgres:postgres@db:5432/chiefonboarding
      - ALLOWED_HOSTS=172.16.19.6
      - ACCOUNT_EMAIL=8********@qq.com
      - ACCOUNT_PASSWORD=*********
    depends_on:
      - db

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/121286783/f2933532-7ff6-48e5-bcf4-da7409414259)
![1711436737672](https://github.com/chiefonboarding/ChiefOnboarding/assets/121286783/fb9b471c-1ba8-414f-98b9-d052a260e4f6)

**Comment by GDay** [comment]
If you are not using https, then you should set `HTTP_INSECURE=True`. If you don't, then the cookies won't be used, since it's not a secure connection and you will keep redirected to the login page (as you noticed). Enabling this setting is not recommended though.
