### ISSUE TITLE
Shows wrong time in Activities for ney employment

### ISSUE THREAD

**Issue by cuseeme** [chiefonboarding/ChiefOnboarding#456]
For the new employees, the wrong time is displayed under the activities on the right.
The time seems to be the normal UTC time and is not displayed based on the timezone that is stored in the settings.
![chief-timedate](https://github.com/chiefonboarding/ChiefOnboarding/assets/1137419/c6bc4914-805f-4f1c-add3-aaa96eb6a027)

**Comment by GDay** [comment]
Thanks for letting me know. Will be fixed when I release the next version.
