### ISSUE TITLE
Being deployable on appstores?

### ISSUE THREAD

**Issue by xboxhaxorz** [chiefonboarding/ChiefOnboarding#458]
I think this would be a great program to use for our non profit animal rescue since this industry tends to go through a lot of volunteers

Any chance this can be made so it is deployable with these?
https://runtipi.io/
https://caprover.com/
https://yunohost.org/#/

Currently i have tipi as that looked to be the simplest to deploy for a noob

**Comment by GDay** [comment]
Anyone is free to add ChiefOnboarding to any of them, but it's unlikely that I will invest any time in that.
