### ISSUE TITLE
Server 500 when uploading file to minio

### ISSUE THREAD

**Issue by zagub59** [chiefonboarding/ChiefOnboarding#463]
Hello everyone, 

I've just set up ChiefOnboarding and everything is working great except for object storage.

I'm using **Nginx Proxy Manager** as my reverse proxy. A minio docker is set up and I've added environments variable in my docker-compose.yml but when I try uploading a file, I always get an error 500 and I don't know where it's coming from. 

When I test minio with a python script, it's working OK so it seems minio is not the root cause ?

Here is **docker-compose.yml of Chiefonboarding**  : 
`version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - /var/chiefonboarding/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chiefonboarding
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    image: chiefonboarding/chiefonboarding:latest
    restart: always
    ports:
      - "8321:8000"
    environment:
      - SECRET_KEY=kdqmlsdkmslkd
      - DATABASE_URL=postgres://postgres:postgres@db:5432/chiefonboarding
      - ALLOWED_HOSTS=welcome.mydomain.com
      - ALLOWED_S3_ENDPOINT_URL=https://buckets.mydomain.com
      - AWS_ACCESS_KEYD_ID=chiefonboarding
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_STORAGE_BUCKET_NAME=chiefonboarding
      - AWS_DEFAULT_REGION=us-east-1
      - SMTP=True
      - EMAIL_HOST=***
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=**@**.com
      - EMAIL_HOST_PASSWORD=*****
      - EMAIL_USE_TLS=True
    depends_on:
      - db
`

Here is my **minio docker-compose.yml**  : 
`version: '2'
services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9999:9001'
    environment:
      - MINIO_ROOT_USER=minioroot
      - MINIO_ROOT_PASSWORD=password
      - MINIO_SERVER_URL=https://buckets.mydomain.com
      - MINIO_BROWSER_REDIRECT_URL=https://buckets-console.mydomain.com
      - MINIO_API_CORS_ALLOW_ORIGIN=https://welcome.mydomain.com
    volumes:
      - minio_storage:/data

volumes:
  minio_storage: {}
`

As for Nginx Proxy Manager:
- Chiefonboarding : subdomain welcome.mydomain.com is redirected to http://IP-of-server:8321 with forced SSL / websockets ON
- Minio API : subdomain buckets.mydomain.com is redirected to https://IP-of-server:9000 with forced SSL / websockets ON
- Minio Console : subdomain buckets-console.mydomain.com is redirected to http://IP-of-server:9999 with forced SSL / websockets ON

Any idea what can cause this issue ?

Thank you for your help!

**Comment by GDay** [comment]
Is the 500 error from minio or from ChiefOnboarding? If it's ChiefOnboarding, then what's the url that gives the 500 error (remove/mask your domain)?

**Comment by zagub59** [comment]
Thanks for your quick answer :) 

The 500 error comes from ChiefOnboarding when I try to upload a picture in a profile or a logo. In the browser console, I get this : 
![Capture d'écran 2024-04-24 223829](https://github.com/chiefonboarding/ChiefOnboarding/assets/63971800/70ef18f8-a5a1-4799-91a6-c7aad664ecd4)

**Comment by GDay** [comment]
That api endpoint gets hit before minio gets hit, so this isn't relevant to minio. Can you try uploading a different file? Only the filename gets passed to that endpoint and I am wonder if there are characters in the filename that ChiefOnboarding is unable to process.

**Comment by GDay** [comment]
Oh, actually, the `ALLOWED_S3_ENDPOINT_URL` isn't correct. That doesn't exist. It should be `AWS_S3_ENDPOINT_URL` and
`AWS_ACCESS_KEYD_ID` has a typo in it `KEYD`.

**Comment by zagub59** [comment]
I tried several filetypes with Chrome and Firefox but I get the same Server 500 issue.

When I try to browse to https://welcome.mydomain.com/api/org/file, I have Server Error (500). Is it a normal behavior ?

**Comment by zagub59** [comment]
Geez I feel stupid. It's been a long day and I did not see the typo ! 

It's all working good now, thank you so much for your quick and efficient help and keep up the good work with this nice tool !

**Comment by GDay** [comment]
No worries. Glad it got resolved! Thanks for letting me know.
