### ISSUE TITLE
Bucket storage, no S3, MinIO issues.

### ISSUE THREAD

**Issue by effectivelywild** [chiefonboarding/ChiefOnboarding#471]
I only have access to blob storage through Azure so I cannot use S3. 

I've spun up a single disk MinIO instance along side the chiefonboarding stack but I have been unable upload any images. I have attempted to do this internally over the docker network using http and https, and externally using http and https with the same result. 

I have enabled debugging within the cheifonboarding web app but do not receive any errors regarding the s3 method, just details about the signed put/get. I have used a variety of other tools to connect to MinIO like s3cli and aws cli both internally and externally without any issues. 

I was also able to copy/paste this bit of boto3 code and update an image (i'm no  developer):

import boto3

```
# Set up MinIO client
s3 = boto3.client('s3',
                  endpoint_url='https://test.com',
                  aws_access_key_id='key',
                  aws_secret_access_key='access_key
# Upload a file to the bucket
s3.upload_file('test.txt', 'cob', 'test.txt')
# List objects in the bucket
response = s3.list_objects(Bucket='cob')
for obj in response.get('Contents', []):
    print(obj['Key'])
```

I did spin up a test bucket on AWS and verified functionality, however I cannot not use S3 for this application.

Any support would be appreciated.

**Comment by GDay** [comment]
Azure blob storage won't work as they don't use an api similar to S3.
MinIO instance without exposing it to the internet won't work as it needs to connect from outside of the container network to the user directly.

> errors regarding the s3 method, just details about the signed put/get.

MinIO with https exposed should work fine. What didn't work as expected? Did you get any errors in the console (right click -> inspect -> console and/or network tab)?

**Comment by fmuise** [comment]
> MinIO with https exposed should work fine. What didn't work as expected? Did you get any errors in the console (right click -> inspect -> console and/or network tab)?

I never thought to check the browser console :tired_face: :cry:

I'm receiving a CORS request error. I did update MinIO to have what I thought to be the correct CORS configuration but at least I have something to troubleshoot now. 

Thanks

**Comment by GDay** [comment]
Great, let me know if you have more issues. I have used Minio before and it worked well with ChiefOnboarding.

**Comment by effectivelywild** [comment]
Turns out it was my reverse proxy adding multiple Access-Control-Allow-Origin headers. Not sure why it was doing this but I manually specified the CORS origin and all is good.

Thanks again.
