### ISSUE TITLE
Change in django.po for productiv systems

### ISSUE THREAD

**Issue by cuseeme** [chiefonboarding/ChiefOnboarding#472]
Hello,
is there a way to replace the translating parts of a language in a production environment?

As an example: 
under back/locale(de/LC_MESSGES/django.po
`
#: users/emails.py:180
#, python-format
msgid "Welcome to %(name)s!"
msgstr "Willkomen %(name)s!"
`
should be changed to:
`
#: users/emails.py:180
#, python-format
msgid "Welcome to %(name)s!"
msgstr "Willkomen bei %(name)s!"
`

**Comment by GDay** [comment]
You can change this, but with the next deployment the changes would be overwritten. 

Could you create a PR instead with the fixes? I will merge them so they will stay correct in new versions.
