### ISSUE TITLE
Footer Version Link Error 404

### ISSUE THREAD

**Issue by floschoepfer** [chiefonboarding/ChiefOnboarding#480]
In the footer is a link to a changelog page of the documentation. When you follow this link, you get an 404 Error, that there is no such page in the documentation:

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/112496896/94b7d759-e4a6-4d44-a14b-aafd071ab0ca)

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/112496896/1a9a8088-05e3-4696-9ab6-1332bbf53a3d)

https://docs.chiefonboarding.com/changelog

**Comment by floschoepfer** [comment]
Maybe change the link to https://github.com/chiefonboarding/ChiefOnboarding/blob/master/CHANGELOG.md ?

**Comment by GDay** [comment]
Good point. I fixed it to that link. Thanks!
