### ISSUE TITLE
Integration - different validations between UI and manifest

### ISSUE THREAD

**Issue by matheuspicioli** [chiefonboarding/ChiefOnboarding#500]
Are you on the latest version of ChiefOnboarding? We only give support for version 2.x.
Yes, v2.2.2

What browser are you using?
Brave

What did you do?
I have configured an integration by "live edition and testing" button, specifically the "revoke" of integration, and it allows me choose `DELETE` method, but when it'll execute throws a 500 error. I noticed this occurs because the manifest that the "live edition and testing" creates is not valid, when I go back to raw manifest and try to save throws error `{"revoke": [{"method": ["\"DELETE\" is not a valid choice."]}]}`
![image](https://github.com/user-attachments/assets/1858169d-3b85-4e09-ad6e-13750fb4ceca)

What did you expect to see?
I expect configure revoke with an `DELET` option, and when I configure by "live edition and testing" the configurations come correctly.

What did you see instead?
Error messages from validation, e.g.: `{"revoke": [{"method": ["\"DELETE\" is not a valid choice."]}]}`

**Comment by matheuspicioli** [comment]
Hi, can you help me please?

**Comment by GDay** [comment]
Just released a new version and that version has a fix for the validation error.

I think the 500 error is not related to the validation error though. Let me know if you have a stack trace from the logs or Sentry or so. Then I can take a look.

Also, we have support plans if you need support quickly. We can't keep up with all issues on Github unfortunately.

**Comment by matheuspicioli** [comment]
Thanks for the update.
Just fixing this validation helps me.
I've tested and it works, thanks!
