### ISSUE TITLE
Integration without exists doesn't appear on `access`

### ISSUE THREAD

**Issue by matheuspicioli** [chiefonboarding/ChiefOnboarding#501]
Are you on the latest version of ChiefOnboarding? We only give support for version 2.x.
Yes, v2.2.2

What browser are you using?
Brave

What did you do?
I have created an integration without an "exists" option configured

What did you expect to see?
I expect see this integration on `Access` tab of my `new hire`

What did you see instead?
I don`t see my integration if it is without `exists` option configured

Is this a normal behavior?

**Comment by GDay** [comment]
Yeah, in that case, we can't check if a user has access or not, which means we can't show the status. In those cases, we don't show that item at all. You can still use it in the sequences if you want to trigger it.

**Comment by matheuspicioli** [comment]
Okay, sounds good to me, thanks
