### ISSUE TITLE
Slackbot getting a 404

### ISSUE THREAD

**Issue by MuratDoganer** [chiefonboarding/ChiefOnboarding#509]
Strange issue has resurfaced! 

Interacting with the bot in Slack gives a 404 error, but the bot is connected to and posts on slack just fine. In the logs I can see this:

``` - - [15/Oct/2024:17:30:51 +0000] "POST /api/slack/bot HTTP/1.1" 404 179 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
 - - [15/Oct/2024:17:31:06 +0000] "POST /api/slack/bot HTTP/1.1" 404 179 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
 - - [15/Oct/2024:17:31:11 +0000] "POST /api/slack/bot HTTP/1.1" 404 179 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
 ```
 
In my Event Subscriptions I get this error, and clicking retry gives the same 404 error:

`Your URL didn't respond with the value of the challenge parameter.`

But the bot posts in Slack just fine!

**Comment by GDay** [comment]
Very strange, haven't released a new version in a while and the slack bot hasn't been updated since august. Weird that you got this so randomly.

I just tested this in my staging environment. And everything seems to work just fine:
- Bot posted a message in a channel
- Clicked button to complete it. 
- Form popped up and I filled it in.
- Submitted form successfully 
- Bot changed message to indicate it was completed.

Have you tried to... turn it off and on again? lol

**Comment by MuratDoganer** [comment]
Yeah its very odd, It was working fine and then it stopped 😄 

I just span up a Render instance to check and it worked without issue, problem is this instance with the error has a lot of data in

and yes it was the first thing I tried lol

**Comment by GDay** [comment]
Hmm... maybe check if Slack rotated the signing secret?

Get into console:
docker compose run --rm web python manage.py shell

Then check the signing secret:
```
from admin.integrations.models import Integration
slack_integration = Integration.objects.get(integration=0)
print(slack_integration.signing_secret)
```

It should match the one in your app dashboard. Go to: https://api.slack.com/apps and then click the app. Then click on "show" next to signing secret.

**Comment by MuratDoganer** [comment]
Hey, sorry for the late reply, I was off and it got hectic when I got back haha

Yes the signing secret is the same and correct

Event Sub is still showing the same URL HTTP error.

Could it be the UFW??

**Comment by GDay** [comment]
Nah, I doubt that. It wouldn't return a 404 in that case.

I have just bumped all dependencies (including Slack) and created a new version. I don't see any related changes in Slack that could cause this, but maybe a fresh docker build or maybe the dependencies fixes your issue.
As always, take a back up before doing the update.
Hopefully this resolves it.

**Comment by MuratDoganer** [comment]
@GDay As mysteriously as it appeared, the issue resolved itself with no input 

Not sure what caused it or what fixed it, but its working again now.
