### ISSUE TITLE
Not able to create a sequence - Title - This field may not be blank - though value is present

### ISSUE THREAD

**Issue by mangatinanda** [chiefonboarding/ChiefOnboarding#67]
Please check the attached screen recording. Though title is given, it is throwing error. Upon inspecting, I see name is `""` in the API call. This is a fresh deployment of code in AWS. 

I was not able to figure out the issue as I am new to vue. Please help.

https://user-images.githubusercontent.com/6745155/116715817-af1d9d00-a9f4-11eb-8d14-47117dc95ed4.mp4

**Comment by GDay** [comment]
Could you try to upload again? It says that the file is corrupt.
Do you know what version you are on?

I just tested creating a new sequence and seems to be working fine for me.

**Comment by GDay** [comment]
Oh, I downloaded the file and now it works. Okay.. You are using the docker setup, I assume? What browser are you using?

**Comment by mangatinanda** [comment]
Namaskaram @GDay Yes it is docker setup. I am using Chrome on Ubuntu 20.04 LTS

Okay, I will try upgrading the setup and try again. Thank you.

**Comment by GDay** [comment]
Hi @mangatinanda . Do you still need help with tihs, or can we close this issue?

**Comment by mangatinanda** [comment]
@GDay Sorry for the late reply. We deployed the latest official docker image and it is working fine. Thank you.

**Comment by GDay** [comment]
Awesome. Thanks for letting me know!
