### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by fw-nytra** [chiefonboarding/ChiefOnboarding#73]
Can you please add smtp support as email provider? 
I have no access to any email provider and I am using my own smtp servers. 
I love ChiefOnboarding!

**Comment by GDay** [comment]
Good to hear that you love ChiefOnboarding! 

I have added SMTP support to v1.2.0: https://github.com/chiefonboarding/ChiefOnboarding/pull/72
Once that's merged, you should update your instance and you should be able to use SMTP. I have already added docs for that: https://docs.chiefonboarding.com/integrations/Email.html (scroll to the bottom)

I will probably merge it on Saturday.

**Comment by GDay** [comment]
Apologies for the massive delay, but the latest version now supports SMTP. I have just pushed it to the main branch and it has been pushed to docker hub! :)
