### ISSUE TITLE
Loading Welcome message does not work

### ISSUE THREAD

**Issue by jeff-99** [chiefonboarding/ChiefOnboarding#8]
Hi @GDay, 

When I try to send a new hire the pre-boarding mail with account credentials I get in the error logs: 

`organization.models.WelcomeMessage.DoesNotExist: WelcomeMessage matching query does not exist.`

I tried running the command to insert these welcome messages: 

`docker-compose run web python3 manage.py loaddata welcome_message.json` 
This gives back an error `CommandError: No fixture named 'welcome_message' found.`

Adding the following to the `settings.py` file fixes the above.

```python
FIXTURE_DIRS=['fixtures']
```

**Comment by GDay** [comment]
Thanks for letting me know. This was actually more of a typo in `README.md` (forgot to prefix `welcome_message.json` with that folder), but this is actually a better solution. 
Just pushed the commit. Thanks for letting me know. 

Fix: https://github.com/chiefonboarding/ChiefOnboarding/commit/862a6c9d553a8a0a3c7b5cb6ecdcf61c1f098a10
