### ISSUE TITLE
Docker setup - Configuring sendgrid email

### ISSUE THREAD

**Issue by mangatinanda** [chiefonboarding/ChiefOnboarding#89]
Have set the env variables like below:

ANYMAIL=True
DEFAULT_FROM_EMAIL=<some valid email>
SENDGRID=True
SENDGRID_KEY=<some valid key>

and restarted the docker container. Still emails are not working. 

Getting 500 error for `api/users/new_hire/4/send_login_email` endpoint. Not able to see logs also. 

Am I missing anything?

**Comment by GDay** [comment]
Hmm.. that's weird. 

Okay, let's debug this a bit. First check the name of the docker container:

```
docker ps
```

Open Django shell by going into the docker container (I am using `chiefonboarding_web` as the docker name here, change it with whatever you have):

```
docker exec -it chiefonboarding_web python manage.py shell
```
Sending email manually (change email address to where you want this test email to go):

```
from django.conf import settings
from django.core.mail import send_mail

send_mail("Test subject", "Test message", settings.DEFAULT_FROM_EMAIL, ["hello@chiefonboarding.com"])
```
The only thing that I have changed here compared to the code in the app, is that I didn't add an HTML email here, but I don't think that will matter much. If it fails, it should show an error message, which should give us more info on why it failed.

If that works, then let's see if you indeed have everything that you need to send the email. You should have a bunch of `WelcomeMessage` records. Try to do this, in that same shell:

```
from organization.models import WelcomeMessage
print(WelcomeMessage.objects.all().count())
```
The number that it shows should be 35.

**Comment by GDay** [comment]
As an update: I just got an email with "Test subject" and "Test message" in the mail. Not sure if it was you, but you probably should have changed the email address (as mentioned above). Just so you know... it worked (if that indeed was you, lol).

**Comment by mangatinanda** [comment]
Hey sorry. Yes, that was me. Changed the email after running that command :| 

WelcomeMessage objects are not present. Did I miss initialising some data?

**Comment by GDay** [comment]
Hah, no worries! 

Okay, that's easy to fix. Previously, this needed to run separated, but with the latest version it doesn't. Anyways run (change `chiefonboarding_web`):

```
docker exec -it chiefonboarding_web python manage.py loaddata welcome_message.json
```
when it's done, it will say that it imported 35 items or so.

**Comment by mangatinanda** [comment]
Thank you so much for patiently helping me. It is working fine now. We will setup the app now.

Before I close, Anything else I would have missed running?

**Comment by GDay** [comment]
You are welcome. Happy to help! 

If you want to load some demo data, then you could run this command as well (change `chiefonboarding_web`):

```
docker exec -it chiefonboarding_web python manage.py loaddata all.json
 ```

**Note:** if you already have some data in the application, then that might get wiped/overwritten by the data in that fixture. So, if you already created some templates/sequences, then it's probably not a good idea to run that.

You should be good to go though!

**Comment by mangatinanda** [comment]
Sure. Thank you so much for your help 🙏  🙇‍♂️
