### ISSUE TITLE
Updating Welcome Message fails

### ISSUE THREAD

**Issue by jeff-99** [chiefonboarding/ChiefOnboarding#9]
Hi @GDay, 

When I try to update the Welcome Message (Pre-boarding email) in the admin portal I get the following error message in my console: 

![image](https://user-images.githubusercontent.com/3385333/88556027-d344eb80-d028-11ea-8124-ca88166382d5.png)

error log:
`Not Found: /api/settings/email_without/`

**Comment by GDay** [comment]
Good catch. Thanks for reporting this issue. Seems like I forgot to add the back end stuff for this. Should be fixed now.
