### ISSUE TITLE
ALLOWED_HOST environment variable

### ISSUE THREAD

**Issue by aokomorowski** [chiefonboarding/ChiefOnboarding#95]
Hey guys, I found some issues with the `ALLOWED_HOST` variable. 

It does allow only one value - so I'm kinda forced to use a wildcard (which defeats the purpose) or one specific URL. 

**Why is it an issue?** 
When using any type of container orchestrator (as AWS ECS) you have to define a health check for the container to keep track of container state. Most of the health check mechanisms will refer to the container by its IP address, which will result in HTTP 400 Bad Request (because an actual IP address is not listed in the `ALLOWED_HOSTS` list). Few unsuccessful checks in a row result in terminating the container. 

**How can it be solved?**
Rename `ALLOWED_HOST` to `ALLOWED_HOSTS` (I wasted a lot of time because of this naming) and parse it into a list, so I, as an admin, can actually provide more than one host header to be allowed. 

Besides that, it would be cool to have a `/health` endpoint to serve as a health check endpoint. It'd return a simple 200 OK response.

**Comment by GDay** [comment]
Had a little bit of time, so I quickly put that together.

You can now use `ALLOWED_HOSTS` (if you, it will ignore the `ALLOWED_HOST` variable - you should probably remove it). 

You can add one URL or multiple, like: `demo.chiefonboarding.com` or `demo.chiefonboarding.com,boom.chiefonboarding.com` - separated by comma).

There is now an extra url (`/health`) which is available regardless of the host/IP address/domainname. It will respond with a 200 status code and `ok` as the content.

Thanks again for the suggestion!

**Comment by aokomorowski** [comment]
Wow, that was quick! I've just deployed `1.2.12` to my ECS cluster. It worked like a charm. Thank you! 🚀
