### ISSUE TITLE
[Bug] Authentication credentials were not provided on clean start

### ISSUE THREAD

**Issue by gruberdev** [chiefonboarding/ChiefOnboarding#97]
# Issue description

- When cloning the repository and executing only `docker-compose up` as per documentation says, you can log in through the API successfully, frontend as well, so the 3 containers have been to be running as intended. 
- However, you cannot access anything on the platform, your login request may get through, but the frontend side freezes at login's page because of a request made to `/api/org/detail` with a message saying `Authentication credentials were not provided`. Even if you try to disable CSRF verification, it may work on the API side, but the frontend side will deny access.

# Environment
- MacOSX Big Sur 11.4
- Macbook Pro i9 2019 16GB 
- Docker-desktop 20.10.7
- Docker-compose 1.29.2, build 5becea4c

If there is a need for more information on this, please feel free to comment on what I should attach or provide in terms of logs or details. Thank you.

**Comment by gruberdev** [comment]
It didn't work because if I were to configure the backend and the frontend to use `HOST=127.0.0.1` the application doesn't know how to communicate to outside of Docker using Macintosh network driver. 

If you try to use the default configuration the URIs don't match, as in, I can't access the application using 0.0.0.0 either. 
I think that I can reconfigure my DNS configuration to force connection to localhost when trying to connect to that IP configuration, I'll try that and report here afterward.

**Comment by GDay** [comment]
I have been able to run the application and use `0.0.0.0:8000` (backend) and `0.0.0.0:3000` (frontend). Which of the two doesn't work on that url for you? Do neither work?

If you want to use `127.0.0.1` then you probably only have to change this line: https://github.com/chiefonboarding/ChiefOnboarding/blob/master/front/nuxt.config.js#L77

Change `0.0.0.0:8000` to `127.0.0.1:8000` there and then restart docker.

**Comment by douglampe** [comment]
I'm running into the same issue. I am running in docker on EC2 in AWS behind an ALB. I am able to get to the login screen using the public IP of the ELB. When I log in, I get the same behavior (login is successful, but accessing the detail page returns 403 so I get sent back to the login. Is there a way to get debug logging via docker so I can see the details of the error? I'm not seeing anything in the log.

**Comment by GDay** [comment]
Don't think there is a way in Docker to find out. 

Have you tried to refresh the page? Also, can you check that the frontend and backend are running on the same URL? With that, including the `http(s)` it should be exactly the same domain name otherwise it will fail for the page you are visiting and where the requests are being made to.

**Comment by douglampe** [comment]
I'm just testing so using the ALB IP address but yes, I have it with HTTP in BASE_URL and also ALLOWED_HOSTS (which also has the private IP since this is what the ALB is using). Also, I'm not using caddy since I'm using an ALB which should be doing the same thing (routing from the external address to the docker server:port).

**Comment by GDay** [comment]
> I'm just testing so using the ALB IP address

That's likely your issue. I assume that doesn't have an SSL certificate. You will need to disable this: https://github.com/chiefonboarding/ChiefOnboarding/blob/08fe7b6887d2732f66ee0a69c05838fe4a63599b/back/back/settings.py#L345-L347

Basically, setting `HTTP_INSECURE` to `True` in your environment settings.

**Comment by GDay** [comment]
Chief is now not using two servers anymore (node + Django -> Django only), so this issue should be gone too (if this was still relevant).
