### ISSUE TITLE
Dockerfile Duplicate

### ISSUE THREAD

**Issue by k----n** [chiefonboarding/ChiefOnboarding#98]
It looks like `https://github.com/chiefonboarding/ChiefOnboarding/blob/master/back/Dockerfile-dev` and `https://github.com/chiefonboarding/ChiefOnboarding/blob/master/back/Dockerfile` are the same.

**Comment by GDay** [comment]
Thanks for the heads-up. 

Actually, they are not the same. If you look closely you can see a small difference here:

https://github.com/chiefonboarding/ChiefOnboarding/blob/master/back/Dockerfile-dev#L11

and 

https://github.com/chiefonboarding/ChiefOnboarding/blob/master/back/Dockerfile#L10

It uses a different kind of `supervisor` config file. This is to separate the development instructions from the normal ones.
